//
//  PlaudWiFiSDK.h
//  PlaudWiFiSDK
//
//  Copyright © 2025 NiceBuild. All rights reserved.
//

#import <Foundation/Foundation.h>

//! Project version number for PlaudWiFiSDK.
FOUNDATION_EXPORT double PlaudWiFiSDKVersionNumber;

//! Project version string for PlaudWiFiSDK.
FOUNDATION_EXPORT const unsigned char PlaudWiFiSDKVersionString[];

// ObjC types from the embedded PenWiFiSDK static library
#import <PlaudWiFiSDK/JXWebSocketServer.h>

// PlaudWiFiSDK-Swift.h is auto-generated by Xcode (all Swift @objc types are
// compiled directly into this framework — no separate PenWiFiSDK module needed).
#if __has_include(<PlaudWiFiSDK/PlaudWiFiSDK-Swift.h>)
#import <PlaudWiFiSDK/PlaudWiFiSDK-Swift.h>
#endif
