#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PLAUDWIFISDK_SWIFT_H
#define PLAUDWIFISDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#import <PlaudWiFiSDK/PlaudWiFiSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PlaudWiFiSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class BleDevice;

/// 一个辅助工具类，方便判断是否连接着WiFi或蓝牙，以及获取BleDevice，调用一些共有的方法
SWIFT_CLASS("_TtC12PlaudWiFiSDK5Agent")
@interface Agent : NSObject
/// 单例
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) Agent * _Nonnull shared;)
+ (Agent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 是否连接着设备（WiFi或者蓝牙）
- (BOOL)isDeviceConnect SWIFT_WARN_UNUSED_RESULT;
/// 如果有一个连着，获取连着的设备信息
- (BleDevice * _Nullable)bleDevice SWIFT_WARN_UNUSED_RESULT;
/// 获取文件列表
/// \param uid 命令id，建议传时间戳
///
/// \param sessionId 起始文件id
///
/// \param single 是否仅获取当前文件信息，默认是否
///
- (void)getFileList:(NSInteger)uid :(NSInteger)sessionId :(BOOL)single;
/// 同步文件
/// \param sessionId 文件id
///
/// \param start 起始偏移量（字节）
///
/// \param end 结束偏移量（字节）
///
/// \param decode 是否同时解码
///
/// \param scene 场景，WiFi才有的参数，默认值1就好
///
- (void)syncFile:(NSInteger)sessionId :(NSInteger)start :(NSInteger)end :(BOOL)decode :(NSInteger)scene;
/// 停止文件同步
/// \param sessionId 文件id，蓝牙状态下不需要
///
/// \param scene 场景，WiFi才有的参数，默认值就好
///
- (void)stopSyncFile:(NSInteger)sessionId :(NSInteger)scene;
/// 删除文件
/// \param sessionId 文件id
///
/// \param scene 场景，WiFi才有的参数，默认值就好
///
- (void)deleteFile:(NSInteger)sessionId :(NSInteger)scene;
/// 正在下载的sessionId（如果有的话）或者正在录音的sessionId（如果正在录音的话）
- (NSInteger)sessionId SWIFT_WARN_UNUSED_RESULT;
/// 是否正在下载
- (BOOL)isDownloading SWIFT_WARN_UNUSED_RESULT;
/// 是否正在录音
- (BOOL)isRecording SWIFT_WARN_UNUSED_RESULT;
@end

@protocol WiFiAgentProtocol;
@class NSString;

/// 需要打开Access WiFi Information和Hotspot Configuration
SWIFT_CLASS("_TtC12PlaudWiFiSDK9WiFiAgent")
@interface WiFiAgent : NSObject
/// 单例
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WiFiAgent * _Nonnull shared;)
+ (WiFiAgent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 用于主动结束WiFi重连（调用connectWiFi会设置为true，主动设置为false后不会继续重连，）
@property (nonatomic) BOOL connectLoop;
/// 当前同步（下载）文件的sessionId
@property (nonatomic, readonly) NSInteger sessionId;
/// 是否正在同步（下载）文件
@property (nonatomic, readonly) BOOL isDownloading;
/// 代理
@property (nonatomic, weak) id <WiFiAgentProtocol> _Nullable delegate;
/// 命令回调线程，默认是主线程
@property (nonatomic, strong) dispatch_queue_t _Nonnull cmdDelegateQueue;
/// 设备信息需要从蓝牙模块传递过来
/// 在蓝牙回调bleWiFiOpen的时候赋值：WiFiAgent.shared.bleDevice = BleAgent.shared.bleDevice
@property (nonatomic, strong) BleDevice * _Nullable bleDevice;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 打开 release 下调试日志，方便追踪问题
- (void)openReleaseLog:(BOOL)opened :(void (^ _Nullable)(NSString * _Nonnull))backBlock;
/// 打开sdk的调试日志，或者回调日志
- (void)openLog:(BOOL)opened :(void (^ _Nullable)(NSString * _Nonnull))backBlock;
/// iOS 11.0以下使用该方法，会循环检查是否已连接到指定WiFi直到超时
/// \param ssid WiFi名称
///
/// \param overtimeSec 超时时间，默认30秒
///
- (void)listenPort:(NSString * _Nonnull)ssid :(NSInteger)overtimeSec;
/// 通过WiFi名称和密码连接到指定WiFi
/// iOS 11.0及以上用这个方法直连WiFi，之前的版本需要弹窗引导用户到设置里面手动连接
/// \param ssid WiFi名称
///
/// \param passphrase 密码
///
/// \param overtimeSec 超时时间，默认60秒
///
- (void)connectWifi:(NSString * _Nonnull)ssid :(NSString * _Nonnull)passphrase :(NSInteger)overtimeSec :(BOOL)needRetry :(NSInteger)hotspotCheckDelaySec :(NSInteger)stallTimeoutSec SWIFT_AVAILABILITY(ios,introduced=11.0);
/// 取消轮询连接 wifi
- (void)cancelConnectWifi;
/// 清理所有WiFi配置缓存
- (void)clearAllWiFiConfigurations SWIFT_AVAILABILITY(ios,introduced=11.0);
/// 清理所有WiFi配置缓存（兼容iOS 11.0以下版本）
- (void)clearAllWiFiConfigurationsCompat;
/// 断开连接
- (void)disconnect;
@end


@interface WiFiAgent (SWIFT_EXTENSION(PlaudWiFiSDK))
/// 获取当前连接的WiFi名称
/// app需要添加Access WiFi Information权限(ios 12.0以后）
- (NSString * _Nullable)getCurrentWiFiName SWIFT_WARN_UNUSED_RESULT;
/// 方法4：带重试机制的WiFi名称获取
- (NSString * _Nullable)getCurrentWiFiNameWithRetryWithMaxRetries:(NSInteger)maxRetries delay:(NSTimeInterval)delay SWIFT_WARN_UNUSED_RESULT;
@end

@class NSData;

@interface WiFiAgent (SWIFT_EXTENSION(PlaudWiFiSDK)) <JXWebSocketServerDelegate>
- (void)serverDidStart;
- (void)serverDidFailWithError:(NSError * _Nonnull)error;
- (void)serverDidStop;
- (void)clientDidOpen;
- (void)clientDidReceiveText:(NSString * _Nonnull)text;
- (void)clientDidReceiveData:(NSData * _Nonnull)data;
- (void)clientDidFailWithError:(NSError * _Nonnull)error;
- (void)clientDidCloseWithCode:(NSInteger)code reason:(NSString * _Nonnull)reason wasClean:(BOOL)wasClean;
@end


@interface WiFiAgent (SWIFT_EXTENSION(PlaudWiFiSDK))
/// 是否已成功建立WebSocket连接（app可以发送请求的前提）
- (BOOL)isWebSocketConnected SWIFT_WARN_UNUSED_RESULT;
/// 速率测试（cmd=100）
/// \param onOff 开始或结束
///
/// \param packSize 测试包大小
///
- (void)appWiFiRate:(BOOL)onOff :(NSInteger)packSize;
/// 删除文件（cmd=14）
/// \param sessionId 录音id
///
/// \param scene 场景，默认1
///
- (void)appDeleteFile:(NSInteger)sessionId :(NSInteger)scene;
/// 延长WiFi退出时间（cmd=16）
- (void)appExtendWifiExitTime;
/// 停止文件同步（cmd=15）
/// \param sessionId 录音id
///
/// \param scene 场景，默认1
///
- (void)appStopSyncFile:(NSInteger)sessionId :(NSInteger)scene;
/// 文件同步（cmd=12）
/// \param sessionId 录音id
///
/// \param start 起始位置（是文件偏移量，不是时间）
///
/// \param end 结束位置（默认0，到文件结束）
///
/// \param scene 录音场景，默认1
///
- (void)appSyncFile:(NSInteger)sessionId :(NSInteger)start :(NSInteger)end :(NSInteger)scene;
/// 获取文件列表（app发起 cmd=11）
/// \param uid 请求的uid，新的请求会自然覆盖老的请求
///
/// \param sessionId 起始sessionId
///
/// \param single 是否仅获取当前文件信息，默认是否，
///
- (void)appGetFileList:(NSInteger)uid :(NSInteger)sessionId :(BOOL)single;
- (void)startPushOTA:(NSInteger)uid :(NSInteger)fileSize crc:(NSInteger)crc :(NSInteger)toVersion;
- (void)sendFilePackToPenWithType:(NSInteger)type start:(int32_t)start len:(int32_t)len last:(BOOL)last uid:(int32_t)uid binData:(NSData * _Nullable)binData;
@end


@class BleFile;
@class WiFiConnectEvent;

SWIFT_PROTOCOL("_TtP12PlaudWiFiSDK17WiFiAgentProtocol_")
@protocol WiFiAgentProtocol
/// 通用错误
/// \param cmd 错误指令
///
/// \param status 错误码
///
- (void)wifiCommonErr:(NSInteger)cmd :(NSInteger)status;
/// 握手结果
/// \param status 0 成功，其他失败
///
- (void)wifiHandshake:(NSInteger)status;
/// 电池电量和电池电压
/// \param power 电池电量，百分比
///
/// \param voltage 电池电压，mv
///
- (void)wifiPower:(NSInteger)power :(NSInteger)voltage;
/// 获取录音列表失败
/// \param status 错误码
///
- (void)wifiFileListFail:(NSInteger)status;
/// 获取录音列表
/// \param files 录音列表
///
- (void)wifiFileList:(NSArray<BleFile *> * _Nonnull)files;
/// 文件同步–文件状态
/// \param sessionId 录音id
///
/// \param status 状态
///
- (void)wifiSyncFile:(NSInteger)sessionId :(NSInteger)status;
/// 文件同步–文件数据
/// \param sessionId 录音id
///
/// \param offset 文件偏移量(字节）
///
/// \param count 文件长度(字节）
///
/// \param binData 数据
///
- (void)wifiSyncFileData:(NSInteger)sessionId :(NSInteger)offset :(NSInteger)count :(NSData * _Nonnull)binData;
/// 一个文件下载完了
- (void)wifiDataComplete;
/// 文件同步停止
/// \param status 状态 0 成功
///
- (void)wifiSyncFileStop:(NSInteger)status;
/// 文件删除结果
/// \param sessionId 录音id
///
/// \param status 删除结果 0 成功，>0 失败原因
///
- (void)wifiFileDelete:(NSInteger)sessionId :(NSInteger)status;
@optional
/// iOS已成功连接到目标WiFi热点（设备开始监听端口前触发，对应Android的wifiConnected回调）
/// 声明为 optional 以保持向后兼容，避免历史 conformer 必须实现
- (void)wifiConnected;
@required
/// 客户端异常断开，等待重连
/// 请设置 BleAgent.shared.setWiFiState(false)
- (void)wifiClientFail;
/// WiFi关闭通知
/// \param status 状态  -1 是 didFailWithError; -2 是超时未连接; -3 NEHotspotConfigurationManager直连异常
///
- (void)wifiClose:(NSInteger)status;
/// 速率测试失败
/// \param status 错误码
///
- (void)wifiRateFail:(NSInteger)status;
/// 速率测试
/// \param instantRate 瞬时速率
///
/// \param averageRate 平均速率
///
/// \param lossRate 丢包率
///
- (void)wifiRate:(NSInteger)instantRate :(NSInteger)averageRate :(double)lossRate;
/// 获取笔端日志失败
/// \param status 错误码
///
- (void)wifiLogsFail:(NSInteger)status;
/// 笔端日志
/// \param logData 日志数据
///
- (void)wifiLogs:(NSData * _Nullable)logData;
/// 笔端发送tips给app
/// \param tips 0 无提示 1 笔端录音键按下
///
- (void)wifiTips:(NSInteger)tips;
- (void)penRequestOTADataWithStart:(NSInteger)start end:(NSInteger)end payloadSize:(NSInteger)payloadSize uid:(NSInteger)uid sendRatePPS:(NSInteger)sendRatePPS;
- (void)wifiOTAStatus:(NSInteger)status :(NSInteger)uid;
@optional
/// 连接状态变更回调
/// 本期仅用于「连接停滞」回抛（trigger=stallThreshold，配合 App 传入的阈值）；
/// 其余连接阶段（wifiConnected/handshaking/… ）为占位，后续接入。
/// optional 保证历史 conformer 无需实现，向后兼容。
- (void)onWiFiConnectStateChanged:(WiFiConnectEvent * _Nonnull)event;
@end

enum WiFiConnectStage : NSInteger;
enum WiFiConnectReason : NSInteger;

/// 连接状态事件：阶段 + 原因。
SWIFT_CLASS("_TtC12PlaudWiFiSDK16WiFiConnectEvent")
@interface WiFiConnectEvent : NSObject
@property (nonatomic, readonly) enum WiFiConnectStage stage;
@property (nonatomic, readonly) enum WiFiConnectReason reason;
- (nonnull instancetype)initWithStage:(enum WiFiConnectStage)stage reason:(enum WiFiConnectReason)reason OBJC_DESIGNATED_INITIALIZER;
/// 序列化为跨 channel 的 dictionary（native → Flutter），字段与设计文档一致。
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 事件原因。说明失败/超时/停滞等「为什么」；正常进展为 none。
typedef SWIFT_ENUM(NSInteger, WiFiConnectReason, open) {
  WiFiConnectReasonNone = 0,
  WiFiConnectReasonPersonalHotspot = 1,
  WiFiConnectReasonConnectSlow = 2,
  WiFiConnectReasonTimeout = 3,
  WiFiConnectReasonFailed = 4,
};

/// 连接阶段。rawValue(code) 为三端契约锚点，只可末尾追加，不可改值/改序。
typedef SWIFT_ENUM(NSInteger, WiFiConnectStage, open) {
  WiFiConnectStageWifiIdle = 0,
  WiFiConnectStageWifiConnecting = 1,
  WiFiConnectStageWifiConnected = 2,
  WiFiConnectStageWifiHandshaking = 3,
  WiFiConnectStageWifiSocketConnected = 4,
  WiFiConnectStageWifiReady = 5,
  WiFiConnectStageWifiConnectFailed = 6,
  WiFiConnectStageWifiClosed = 7,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
