#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PLAUDDEVICEBASICSDK_SWIFT_H
#define PLAUDDEVICEBASICSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import PlaudBleSDK;
@import PlaudWiFiSDK;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PlaudDeviceBasicSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@interface AVAudioPlayer (SWIFT_EXTENSION(PlaudDeviceBasicSDK)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)_ successfully:(BOOL)flag;
- (void)audioPlayerDecodeErrorDidOccur:(AVAudioPlayer * _Nonnull)_ error:(NSError * _Nullable)error;
@end


typedef SWIFT_ENUM(NSInteger, AudioDecryptorError, open) {
  AudioDecryptorErrorInvalidHeader = 1,
  AudioDecryptorErrorInvalidSymmetricKey = 2,
  AudioDecryptorErrorNoEncryptedData = 3,
  AudioDecryptorErrorDecryptionFailed = 4,
};
static NSString * _Nonnull const AudioDecryptorErrorDomain = @"PlaudDeviceBasicSDK.AudioDecryptorError";

@class NSString;

/// 音频导出回调协议（与 Android AudioExporter.ExportCallback 一致）
SWIFT_PROTOCOL("_TtP19PlaudDeviceBasicSDK19AudioExportCallback_")
@protocol AudioExportCallback
/// 导出进度更新
/// \param progress 进度百分比 (0-100)
///
/// \param message 状态消息
///
- (void)onProgress:(NSInteger)progress message:(NSString * _Nonnull)message;
/// 导出完成
/// \param outputPath 输出文件路径
///
- (void)onCompleteWithOutputPath:(NSString * _Nonnull)outputPath;
/// 导出失败
/// \param error 错误信息
///
- (void)onError:(NSString * _Nonnull)error;
@end

/// 音频导出格式枚举（与 Android AudioExportFormat 一致）
/// 定义了 SDK 支持的音频导出格式
typedef SWIFT_ENUM(NSInteger, AudioExportFormat, open) {
/// PCM 格式 - 原始音频数据
/// 需要知道采样率和声道数才能正确播放
/// 16kHz, 16-bit, mono
  AudioExportFormatPcm = 0,
/// MP3 格式 - LAME 编码
/// 通用播放格式，兼容性最好
  AudioExportFormatMp3 = 1,
/// WAV 格式（推荐）
/// 带头信息的 PCM，可直接播放
/// 包含采样率、声道数等元数据
  AudioExportFormatWav = 2,
/// Opus 格式 - OGG/Opus 容器
/// 高压缩比，适合语音，文件体积小
  AudioExportFormatOpus = 3,
};

@class PlaudEncryptHeader;

/// Audio file E2EE decryptor for NotePro devices.
/// NotePro audio files have two encryption layers:
/// <ol>
///   <li>
///     BLE Transport Layer - ChaCha20-Poly1305 (handled by BleAgent)
///   </li>
///   <li>
///     File Content Layer - RSA encrypted key header + ChaCha20 encrypted data (handled here)
///   </li>
/// </ol>
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK18AudioFileDecryptor")
@interface AudioFileDecryptor : NSObject
/// Decrypt an E2EE encrypted audio file
/// \param inputPath The encrypted audio file path
///
/// \param privateKeyPem The RSA private key in PEM format
///
/// \param outputPath Optional output file path. If nil, creates a temp file
///
///
/// returns:
/// The decrypted audio file path, or original path if not encrypted
+ (NSString * _Nullable)decryptAudioFileWithInputPath:(NSString * _Nonnull)inputPath privateKeyPem:(NSString * _Nonnull)privateKeyPem outputPath:(NSString * _Nullable)outputPath error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// Check if a file is E2EE encrypted
+ (BOOL)isFileEncryptedWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
/// Get the PlaudEncryptHeader from a file
+ (PlaudEncryptHeader * _Nullable)getHeaderWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface BleAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
/// 解密 E2EE 加密的音频文件
- (NSString * _Nullable)decryptE2EEAudioFileWithInputPath:(NSString * _Nonnull)inputPath outputPath:(NSString * _Nullable)outputPath privateKeyPem:(NSString * _Nonnull)privateKeyPem error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isE2EEEncryptedFileWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
- (PlaudEncryptHeader * _Nullable)getE2EEFileHeaderWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
@end


@interface BleAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
@property (nonatomic, readonly) BOOL isEncryptionSupported;
- (NSDictionary<NSString *, id> * _Nonnull)getEncryptionProtocolInfo SWIFT_WARN_UNUSED_RESULT;
@end

@protocol JXOggPlayerDelegate;
@class JXOggPlayer;

@interface BleAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
- (BOOL)playDecryptedOggFileWithEncryptedFilePath:(NSString * _Nonnull)encryptedFilePath channel:(int32_t)channel delegate:(id <JXOggPlayerDelegate> _Nullable)delegate key:(NSString * _Nullable)key nonce:(NSString * _Nullable)nonce ad:(NSString * _Nullable)ad SWIFT_WARN_UNUSED_RESULT;
- (void)stopOggPlayback;
- (void)pauseOggPlayback;
- (void)resumeOggPlayback;
- (JXOggPlayer * _Nonnull)getOggPlayer SWIFT_WARN_UNUSED_RESULT;
@end

@class NSData;

@interface BleAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
/// 是否已建立加密通道
@property (nonatomic, readonly) BOOL isSecureChannelEstablished;
/// 获取当前加密密钥（Base64编码，用于文件解密）
- (NSString * _Nullable)getEncryptionKey SWIFT_WARN_UNUSED_RESULT;
/// 获取当前加密Nonce（Base64编码）
- (NSString * _Nullable)getEncryptionNonce SWIFT_WARN_UNUSED_RESULT;
/// 获取当前加密AD（Base64编码）
- (NSString * _Nullable)getEncryptionAD SWIFT_WARN_UNUSED_RESULT;
/// 获取完整的加密参数
- (NSDictionary<NSString *, NSString *> * _Nullable)getEncryptionParameters SWIFT_WARN_UNUSED_RESULT;
/// 解密加密的OGG文件数据
- (NSData * _Nullable)decryptFileData:(NSData * _Nonnull)encryptedData key:(NSString * _Nullable)key nonce:(NSString * _Nullable)nonce ad:(NSString * _Nullable)ad error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// 解密加密的OGG文件
- (BOOL)decryptFileWithInputPath:(NSString * _Nonnull)inputPath outputPath:(NSString * _Nonnull)outputPath key:(NSString * _Nullable)key nonce:(NSString * _Nullable)nonce ad:(NSString * _Nullable)ad SWIFT_WARN_UNUSED_RESULT;
/// 解密并准备OGG文件
- (NSString * _Nullable)decryptAndPrepareOggFileWithEncryptedFilePath:(NSString * _Nonnull)encryptedFilePath channel:(int32_t)channel key:(NSString * _Nullable)key nonce:(NSString * _Nullable)nonce ad:(NSString * _Nullable)ad SWIFT_WARN_UNUSED_RESULT;
@end





typedef SWIFT_ENUM(NSInteger, EncryptionError, open) {
  EncryptionErrorNoKey = 1,
  EncryptionErrorNoNonce = 2,
  EncryptionErrorNoAD = 3,
  EncryptionErrorDataTooShort = 4,
  EncryptionErrorDecryptionFailed = 5,
};
static NSString * _Nonnull const EncryptionErrorDomain = @"PlaudDeviceBasicSDK.EncryptionError";




/// Latest version response model
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK21LatestVersionResponse")
@interface LatestVersionResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull model;
@property (nonatomic, readonly, copy) NSString * _Nonnull version_type;
@property (nonatomic, readonly, copy) NSString * _Nonnull version_code;
@property (nonatomic, readonly, copy) NSString * _Nonnull version_number;
@property (nonatomic, readonly, copy) NSString * _Nonnull version_description;
@property (nonatomic, readonly) BOOL is_force;
@property (nonatomic, readonly) BOOL is_strong_guidance;
@property (nonatomic, readonly, copy) NSString * _Nullable file_md5;
@property (nonatomic, readonly, copy) NSString * _Nonnull download_url;
/// Compatibility property: version number (mapped to version_number)
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
/// Compatibility property: release notes (mapped to version_description)
@property (nonatomic, readonly, copy) NSString * _Nullable release_notes;
/// Compatibility property: force update (mapped to is_force)
@property (nonatomic, readonly) BOOL force_update;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




/// Parser for standard Ogg/Opus format files
/// Used for E2EE decrypted audio files which are in standard OGG format
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK13OggOpusParser")
@interface OggOpusParser : NSObject
/// Reset the shared decoder (no-op, JXOpusDecoder manages its own lifecycle)
+ (void)resetDecoder;
@property (nonatomic, readonly) NSInteger parsedSampleRate;
@property (nonatomic, readonly) NSInteger parsedChannels;
@property (nonatomic, readonly) NSInteger parsedPreSkip;
/// Parse Ogg Opus data and extract all Opus frames
/// \param oggData The Ogg Opus file data
///
///
/// returns:
/// Array of raw Opus frames
- (NSArray<NSData *> * _Nonnull)parse:(NSData * _Nonnull)oggData SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;
@class NSBundle;

SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK30PlaudAudioPlayerViewController")
@interface PlaudAudioPlayerViewController : UIViewController <AVAudioPlayerDelegate>
- (nonnull instancetype)initWithSessionId:(NSInteger)sessionId OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)_ SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)_ successfully:(BOOL)flag;
- (void)audioPlayerDecodeErrorDidOccur:(AVAudioPlayer * _Nonnull)_ error:(NSError * _Nullable)error;
- (void)audioPlayerBeginInterruption:(AVAudioPlayer * _Nonnull)_;
- (void)audioPlayerEndInterruption:(AVAudioPlayer * _Nonnull)_ withOptions:(NSUInteger)_;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_RESILIENT_CLASS("_TtC19PlaudDeviceBasicSDK14PlaudBleDevice")
@interface PlaudBleDevice : BleDevice
- (nonnull instancetype)initWithSn:(NSString * _Nonnull)sn OBJC_DESIGNATED_INITIALIZER;
@end

@protocol PlaudDeviceAgentProtocol;
enum PlaudDownloadFormat : NSInteger;

SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK16PlaudDeviceAgent")
@interface PlaudDeviceAgent : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaudDeviceAgent * _Nonnull shared;)
+ (PlaudDeviceAgent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 当前 BLE 下载速度(KB/s)。与 <code>PlaudWiFiAgent.currentDownloadSpeedKBps</code> 对称，App 两端可用同一套读取逻辑。
@property (nonatomic, readonly) double currentDownloadSpeedKBps;
/// 格式化下载速度字符串(如 “1.2 MB/s” / “300.0 KB/s”)。
- (NSString * _Nonnull)getFormattedDownloadSpeed SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) BleDevice * _Nullable recentConnectDevice;
@property (nonatomic, readonly) NSInteger sceneFlag;
/// WiFi 快传进行中标记，抑制 BLE 断连时的缓存清除和自动重连
@property (nonatomic, readonly) BOOL isWiFiTransferActive;
/// 是否跳过 SDK 权限检查（NotePro 新固件不需要传统的 appKey/appSecret 权限验证）
@property (nonatomic) BOOL skipPermissionCheck;
@property (nonatomic, weak) id <PlaudDeviceAgentProtocol> _Nullable delegate;
/// Current recording file or sync (download) file sessionId
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Initialize SDK (recommended)
/// \param userAccessToken User Access Token (JWT)，用于设备认证、sn-sign、gen-key。
/// 握手 token 自动从 JWT sub 字段解析，无需手动传入。
///
/// \param customDomain 服务端域名（如 “platform-us.plaud.ai”），不含 https://。
/// SDK 所有网络请求都使用此域名。
///
/// \param extra 额外参数（可选）
///
- (void)initSDKWithUserAccessToken:(NSString * _Nonnull)userAccessToken customDomain:(NSString * _Nonnull)customDomain extra:(NSDictionary<NSString *, NSString *> * _Nonnull)extra SWIFT_METHOD_FAMILY(none);
/// Initialize SDK (legacy, 兼容旧版本)
/// \param hostName （已废弃）服务端 URL，被 customDomain 替代
///
/// \param appKey （已废弃）App key
///
/// \param appSecret （已废弃）App secret
///
/// \param bindToken （已废弃）握手 token，当 partnerToken 存在时自动从 JWT sub 字段解析
///
/// \param extra 额外参数
///
/// \param customDomain 服务端域名（如 “platform-us.plaud.ai”），不含 https://
///
/// \param partnerToken （已废弃）请使用 userAccessToken 参数。User Access Token (JWT)
///
- (void)initSDKWithHostName:(NSString * _Nonnull)hostName appKey:(NSString * _Nonnull)appKey appSecret:(NSString * _Nonnull)appSecret bindToken:(NSString * _Nonnull)bindToken extra:(NSDictionary<NSString *, NSString *> * _Nonnull)extra customDomain:(NSString * _Nullable)customDomain partnerToken:(NSString * _Nullable)partnerToken SWIFT_METHOD_FAMILY(none);
/// 动态更新 User Access Token
/// 可在 SDK 初始化后调用，token 刷新时使用
/// \param token User Access Token (JWT)
///
- (void)setUserAccessToken:(NSString * _Nullable)token;
/// （已废弃）请使用 setUserAccessToken
- (void)setPartnerToken:(NSString * _Nullable)token SWIFT_DEPRECATED_MSG("", "setUserAccessToken:");
/// 检查 Partner API 数据是否已准备好
- (BOOL)isPartnerDataReady SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getTestAppKey:(BOOL)beta SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)getTestAppSecret:(BOOL)beta SWIFT_WARN_UNUSED_RESULT;
- (void)depairWithClear:(BOOL)clear;
- (void)setDeviceWiFiWithOpen:(BOOL)open;
/// 结束 WiFi 快传模式（WiFi 断开后调用，恢复 BLE 正常行为）。
/// 1.0.10 起：BLE 可用时会同时请求设备关闭热点（等效自动补调 setDeviceWiFi(false)），
/// 避免接入方漏调导致设备滞留 WiFi 模式直至固件超时（约 2 分钟）。
- (void)endWiFiTransfer;
- (void)setDeviceBindingWithToken:(NSString * _Nonnull)token;
/// Start scan
/// @see        stopScan()
/// @see        Callback bleScanResult
- (void)startScan;
/// End scan
/// @see        startScan()
- (void)stopScan;
- (BOOL)isConnected SWIFT_WARN_UNUSED_RESULT;
/// Connect bluetooth device
/// \param bleDevice Wrapped bluetooth device
///
/// \param deviceToken device token
/// @see    Callback bleConnectState
/// @see    Callback bleBind
///
- (void)connectBleDeviceWithBleDevice:(BleDevice * _Nonnull)bleDevice deviceToken:(NSString * _Nonnull)deviceToken;
/// Connect bluetooth device
/// \param bleDevice Wrapped bluetooth device
/// @see    Callback bleConnectState
/// @see    Callback bleBind
///
- (void)connectBleDeviceWithBleDevice:(BleDevice * _Nonnull)bleDevice;
/// 砖机恢复连接：以历史绑定用户的身份发起一次连接，并让设备清除其存量的绑定密钥材料
/// 适用场景：设备曾被用户 A 绑定、云端已解绑但固件仍保留 A 的绑定信息（“砖机”），
/// 当前用户 B 正常连接会在加密预握手阶段被设备拒绝/断开（设备 pin 了 A 的 RSA 公钥）。
/// 行为：
/// <ol>
///   <li>
///     historicalUserId 接受 bind_history 的 client_user_id 原文或 32hex 两种形式，统一变换后临时钉住为握手 token；
///   </li>
///   <li>
///     以 isForceClear=true 发起连接（预握手使用 PRE_HANDSHAKE_AND_CLEAR 0xFE20，设备清除存量密钥材料）；
///   </li>
///   <li>
///     加密材料（sn-sign / RSA 密钥对）仍使用当前登录用户的，无需为历史用户签发；
///   </li>
///   <li>
///     连接结束（depair 后断开、或失败）时自动还原当前用户握手身份。
///   </li>
/// </ol>
/// 成功握手后调用 depair() 清除设备绑定，等设备重新广播（depair 后 MAC 会变化，必须重新扫描），
/// 再以当前用户正常 connectBleDevice 完成重新绑定。
/// @see Callback bleConnectState / bleBind / bleConnectStage
- (void)recoveryConnectBleDeviceWithBleDevice:(BleDevice * _Nonnull)bleDevice historicalUserId:(NSString * _Nonnull)historicalUserId;
/// Disconnect bluetooth connection
- (void)disconnect;
- (void)tryReconnectLastDevice;
/// Read recorder status, return state and privacy status
/// @see    Callback blePenState
- (void)getState;
/// Read recorder remaining space
/// @see    Callback bleStorage
- (void)getStorage;
/// Wifi sync switch
/// @see    Callback onWifiSyncEnabled
- (void)getWifiSyncEnable;
/// Wifi sync switch
/// \param value 0: off 1: on
///
- (void)setWifiSyncEnableWithValue:(NSInteger)value;
/// Initiate idle sync Wi-Fi test
/// \param wifiIndex Wi-Fi number (4 bytes)
///
- (void)setWifiSyncTestWithWifiIndex:(uint32_t)wifiIndex;
/// Get idle sync Wi-Fi test result
/// \param wifiIndex Wi-Fi number (4 bytes)
///
- (void)getWifiSyncTestResultWithWifiIndex:(uint32_t)wifiIndex;
/// Get battery level status
/// @see    Callback blePowerChange
/// @see    Callback bleChargingState
- (void)getChargingState;
/// Set microphone gain
/// \param value Microphone gain value, range 0 - 30
///
- (void)setMicGainWithValue:(NSInteger)value;
/// Get microphone gain
/// @see    bleMicGain
- (void)readMicGain;
/// Enable U disk mode
/// \param onOff 1 enable; 0 disable
///
- (void)setUDiskModeOnOff:(BOOL)onOff;
- (BOOL)checkIsRecording SWIFT_WARN_UNUSED_RESULT;
- (BOOL)checkIsDownloading SWIFT_WARN_UNUSED_RESULT;
/// Start recording
/// If recording starts successfully, need to call syncFile to sync file yourself
/// Can display real-time recording duration through sync file offset
/// @see    Callback bleRecordStart
- (void)startRecord;
/// Wake/sleep setting
/// 0: sleep; 1: wake
- (void)setDeviceActiveWithStatus:(NSInteger)status;
/// Stop current recording
/// @see    Callback bleRecordStop
- (void)stopRecord;
/// Set device name
- (void)setDeviceName:(NSString * _Nonnull)name;
- (NSInteger)getCurrentSessionID SWIFT_WARN_UNUSED_RESULT;
/// Pause recording
/// Resume through resumeRecord()
/// @see    Callback bleRecordPause
- (void)pauseRecord;
/// Resume recording
/// @see Callback bleRecordResume
- (void)resumeRecord;
/// Get session list (get file list after a certain sessionId)
/// This command is not available during recording
/// This command is not available in U disk mode
/// \param uid Used to distinguish different commands
///
/// \param sessionId Which file to start syncing from, 0 means sync all
/// @see    Callback bleFileList
///
- (void)getFileListWithStartSessionId:(NSInteger)startSessionId;
/// This command is not available during recording
/// This command is not available in U disk mode
/// \param sessionId File id
/// Query file corresponding to this sessionId (get real-time recording file length after real-time recording ends)
/// @see    Callback bleFileList
///
- (void)getFileWithSessionId:(NSInteger)sessionId;
/// Sync (download) file
/// \param sessionId Recording file unique id
///
/// \param start Recording file start position (bytes)
///
/// \param end Sync to where? Generally pass 0, means sync to file end (bytes)
/// @see    Callback bleSyncFileHead
/// @see    Callback bleSyncFileTail
/// @see    Callback bleData
/// @see    Callback bleDecodeFail
/// @see    Callback bleDataComplete
/// @see    Callback blePcmData
///
- (void)syncFileWithSessionId:(NSInteger)sessionId start:(NSInteger)start end:(NSInteger)end;
/// Download composite file (complete file)
/// \param sessionId File unique ID
///
/// \param desiredOutputPath Desired output path (without extension)
///
/// \param format Output format. Options: .wav (recommended, playable), .pcm (raw audio data)
/// @see    Callback bleDownloadFile
///
- (void)downloadFileWithSessionId:(NSInteger)sessionId desiredOutputPath:(NSString * _Nonnull)desiredOutputPath format:(enum PlaudDownloadFormat)format;
/// Stop file download
/// @see    Callback bleDownloadFileStop
- (void)stopDownloadFile;
/// 导出音频文件（与 Android SDK 接口一致）
/// 此方法会自动完成以下步骤：
/// <ol>
///   <li>
///     检查本地是否已有缓存文件
///   </li>
///   <li>
///     如果没有，从设备下载文件
///   </li>
///   <li>
///     进行 E2EE 解密（如果需要）
///   </li>
///   <li>
///     转换为目标格式并保存
///   </li>
/// </ol>
/// <ul>
///   <li>
///     Example:
///   </li>
/// </ul>
/// \code
/// // Android:
/// // NiceBuildSdk.exportAudio(sessionId, outputDir, format, channels, callback)
/// //
/// // iOS:
/// deviceAgent.exportAudio(
///     sessionId: 1234567890,
///     outputDir: documentsPath,
///     format: .wav,
///     channels: 1,
///     callback: self
/// )
///
/// \endcode\param sessionId 录音文件唯一标识
///
/// \param outputDir 输出目录路径
///
/// \param format 输出格式 (.wav 推荐, .pcm)
///
/// \param channels 声道数（默认 1，单声道）
///
/// \param callback 导出回调（进度、完成、错误）
///
- (void)exportAudioWithSessionId:(NSInteger)sessionId outputDir:(NSString * _Nonnull)outputDir format:(enum AudioExportFormat)format channels:(NSInteger)channels callback:(id <AudioExportCallback> _Nonnull)callback;
/// End file sync (download)
/// @see    Callback bleSyncFileStop
- (void)stopSyncFile;
/// Delete file
/// \param sessionId Recording file unique id
/// @see    Callback bleDeleteFile
///
- (void)deleteFileWithSessionId:(NSInteger)sessionId;
/// Clear all files
/// @see    Callback bleClearAllFile
- (void)clearAllFiles;
/// Factory reset
/// No callback
- (void)restoreFactory;
/// Get idle sync WiFi configuration
/// \param wifiIndex Wi-Fi number (4 bytes)
///
- (void)getWifiSyncConfigWithWifiIndex:(uint32_t)wifiIndex;
/// Set idle sync WiFi configuration
/// \param operation Operation type 1: add, 2: modify)
///
/// \param wifiIndex Wi-Fi number (4 bytes)
///
/// \param ssid Wi-Fi SSID
///
/// \param password Wi-Fi password
///
- (void)setWifiSyncConfigWithOperation:(NSInteger)operation wifiIndex:(uint32_t)wifiIndex ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password;
/// Get idle sync WiFi list
- (void)getWifiSyncList;
/// Delete idle sync WiFi configuration
/// \param wifiIndices Array of Wi-Fi numbers to delete (each number is 4 bytes)
///
- (void)deleteWifiSyncConfigWithWifiIndices:(NSArray<NSNumber *> * _Nonnull)wifiIndices;
@end





@interface PlaudDeviceAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
- (void)onBinaryFileReqWithType:(NSInteger)type packageOffset:(NSInteger)packageOffset packageSize:(NSInteger)packageSize endStatus:(NSInteger)endStatus;
- (void)onBinaryFileEndWithResult:(NSInteger)result;
@end


@interface PlaudDeviceAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
/// Clears the stored SDK credentials (AppKey and AppSecret) from UserDefaults
- (void)clearSDKCredentials;
@end



@interface PlaudDeviceAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
/// Show update confirmation alert
/// \param versionInfo version information
///
/// \param completion user selection callback
///
- (void)showUpdateConfirmationWithVersionInfo:(LatestVersionResponse * _Nonnull)versionInfo completion:(void (^ _Nonnull)(BOOL))completion;
/// Simplified check for latest version for Objective-C
/// \param model Device model (required)
///
/// \param snType Device type, options: note, notepin, notepro, other, default: notepin
///
/// \param versionType Version type, options: T, G, V, default: V
///
/// \param hasUpdate Callback with update available flag and version info
///
/// \param failure Failure callback with error message
///
- (void)checkLatestVersionForModel:(NSString * _Nonnull)model snType:(NSString * _Nonnull)snType versionType:(NSString * _Nonnull)versionType hasUpdate:(void (^ _Nonnull)(BOOL, LatestVersionResponse * _Nullable))hasUpdate failure:(void (^ _Nonnull)(NSString * _Nonnull))failure;
/// Simplified download update for Objective-C
/// \param versionInfo Version information to download
///
/// \param progress Progress callback with percentage (0.0 to 1.0)
///
/// \param success Success callback with local file path
///
/// \param failure Failure callback with error message
///
- (void)downloadUpdateForVersion:(LatestVersionResponse * _Nonnull)versionInfo progress:(void (^ _Nonnull)(float))progress success:(void (^ _Nonnull)(NSString * _Nonnull))success failure:(void (^ _Nonnull)(NSString * _Nonnull))failure;
@end

@class PlaudFirmwareCheckResult;
enum PlaudFirmwarePhase : NSInteger;
@class PlaudFirmwareUpdateResult;

@interface PlaudDeviceAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
/// 上报设备元数据（电量、固件版本、存储等）
/// 连接成功后 SDK 自动调用，App 层通常无需手动调用
- (void)reportDeviceMetadata;
- (void)checkFirmwareUpdateWithCompletion:(void (^ _Nonnull)(PlaudFirmwareCheckResult * _Nonnull))completion;
- (void)startFirmwareUpdateWithProgress:(void (^ _Nonnull)(enum PlaudFirmwarePhase, float))progress completion:(void (^ _Nonnull)(PlaudFirmwareUpdateResult * _Nonnull))completion;
- (void)pushFirmwareFileWithFilePath:(NSString * _Nonnull)filePath toVersion:(NSString * _Nonnull)toVersion progress:(void (^ _Nonnull)(enum PlaudFirmwarePhase, float))progress completion:(void (^ _Nonnull)(PlaudFirmwareUpdateResult * _Nonnull))completion;
@end


@class BleFile;
@class BleRecordMarkingTag;

@interface PlaudDeviceAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK)) <BleAgentProtocol>
- (void)bleScanResultWithBleDevices:(NSArray<BleDevice *> * _Nonnull)bleDevices;
- (void)bleScanOverTime;
- (void)bleAppKeyStateWithResult:(NSInteger)result;
- (void)bleConnectStageWithSn:(NSString * _Nullable)sn stage:(NSString * _Nonnull)stage detail:(NSString * _Nullable)detail;
- (void)bleConnectStateWithState:(NSInteger)state;
- (void)bleBindWithSn:(NSString * _Nullable)sn status:(NSInteger)status protVersion:(NSInteger)protVersion timezone:(NSInteger)timezone;
- (void)blePenStateWithState:(NSInteger)state privacy:(NSInteger)privacy keyState:(NSInteger)keyState uDisk:(NSInteger)uDisk findMyToken:(NSInteger)findMyToken hasSndpKey:(NSInteger)hasSndpKey deviceAccessToken:(NSInteger)deviceAccessToken versionType:(NSString * _Nonnull)versionType versionCode:(NSInteger)versionCode;
- (void)bleStorageWithTotal:(NSInteger)total free:(NSInteger)free duration:(NSInteger)duration;
- (void)blePowerChangeWithPower:(NSInteger)power oldPower:(NSInteger)oldPower;
- (void)bleChargingStateWithIsCharging:(BOOL)isCharging level:(NSInteger)level;
- (void)bleFileListWithBleFiles:(NSArray<BleFile *> * _Nonnull)bleFiles;
- (void)bleDataComplete;
- (void)bleRecordStartWithSessionId:(NSInteger)sessionId start:(NSInteger)start status:(NSInteger)status scene:(NSInteger)scene startTime:(NSInteger)startTime;
- (void)bleRecordStopWithSessionId:(NSInteger)sessionId reason:(NSInteger)reason fileExist:(BOOL)fileExist fileSize:(NSInteger)fileSize;
- (void)bleRecordPauseWithSessionId:(NSInteger)sessionId reason:(NSInteger)reason fileExist:(BOOL)fileExist fileSize:(NSInteger)fileSize;
- (void)bleRecordResumeWithSessionId:(NSInteger)sessionId start:(NSInteger)start status:(NSInteger)status scene:(NSInteger)scene startTime:(NSInteger)startTime;
- (void)bleSyncFileHeadWithSessionId:(NSInteger)sessionId status:(NSInteger)status;
- (void)bleSyncFileTailWithSessionId:(NSInteger)sessionId crc:(NSInteger)crc;
- (void)bleDataWithSessionId:(NSInteger)sessionId start:(NSInteger)start data:(NSData * _Nonnull)data;
- (void)blePcmDataWithSessionId:(NSInteger)sessionId millsec:(NSInteger)millsec pcmData:(NSData * _Nonnull)pcmData isMusic:(BOOL)isMusic;
- (void)bleDecodeFailWithStart:(NSInteger)start;
- (void)bleSyncFileStop;
- (void)bleDeleteFileWithSessionId:(NSInteger)sessionId status:(NSInteger)status;
- (void)bleDepair:(NSInteger)status;
- (void)bleMicGain:(NSInteger)value;
- (void)onSyncIdleWifiConfigReceivedWithIndex:(uint32_t)index ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password;
- (void)onSyncIdleWifiConfigSetWithResult:(NSInteger)result;
- (void)onSyncIdleWifiListReceivedWithList:(NSArray<NSNumber *> * _Nonnull)list;
- (void)onSyncIdleWifiDeleteResultWithResult:(NSInteger)result;
- (void)onSyncIdleWifiTestStartedWithIndex:(uint32_t)index;
- (void)onSyncIdleWillStartWithSeconds:(NSInteger)seconds;
- (void)onSyncIdleWifiTestResultWithIndex:(uint32_t)index result:(NSInteger)result rawCode:(NSInteger)rawCode;
- (void)bleSyncWhenIdleEnabled:(NSInteger)value;
- (void)bleUDiskErrWithFuncName:(NSString * _Nonnull)funcName;
- (void)bleWiFiOpen:(NSInteger)status :(NSString * _Nonnull)wifiName :(NSString * _Nonnull)wholeName :(NSString * _Nonnull)wifiPass;
- (void)bleDeviceNameWithName:(NSString * _Nullable)name;
- (void)bleFotaResultWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
- (void)bleFotaPackReqWithUid:(NSInteger)uid start:(NSInteger)start end:(NSInteger)end;
- (void)bleFotaPackFinWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
- (void)bleOtaDataSendFail;
- (void)bleRateWithLossRate:(double)lossRate rate:(NSInteger)rate instantRate:(NSInteger)instantRate;
- (void)bleSetActiveWithStatus:(NSInteger)status;
- (void)bleIBeaconWakeupEnabled:(NSInteger)value;
- (void)bleSyncOtaFileInfoWithUid:(uint32_t)uid start:(uint32_t)start end:(uint32_t)end toVersion:(uint32_t)toVersion toVersionType:(uint8_t)toVersionType isSilent:(NSInteger)isSilent packetCheckOk:(NSInteger)packetCheckOk;
- (void)bleHeartbeatWithStatus:(NSInteger)status;
- (void)bleBatteryMode:(NSInteger)mode;
- (void)bleDeviceStatusWithStatus:(NSArray<NSNumber *> * _Nonnull)status;
- (void)bleNewFeatureWithData:(NSData * _Nonnull)data;
- (void)bleGetRecordMarkingTagsWithUid:(NSInteger)uid totals:(NSInteger)totals index:(NSInteger)index tags:(NSArray<BleRecordMarkingTag *> * _Nonnull)tags;
- (void)deviceLogDataWithStart:(NSInteger)start data:(NSData * _Nonnull)data logType:(NSInteger)logType;
- (void)onGetDeviceLogListWithData:(NSData * _Nonnull)data;
- (void)onSyncDeviceLogStartWithData:(NSData * _Nonnull)data;
- (void)onSyncDeviceLogStop;
- (void)onSyncDeviceLogEndWithData:(NSData * _Nonnull)data;
- (void)onDeviceLogDeletedWithData:(NSData * _Nonnull)data;
- (void)bleUpdatePowerLowErr;
- (void)bleDeviceDisconnectErr;
- (void)bleStateWithPowered:(BOOL)powered;
- (void)bleHandshakeWaitWithTimeout:(NSInteger)timeout;
- (void)blePenTimeWithStamp:(NSInteger)stamp timezone:(NSInteger)timezone zoneMin:(NSInteger)zoneMin;
- (void)blePasswordResetWithPassword:(NSInteger)password;
- (void)bleBacklightDuration:(NSInteger)duration;
- (void)bleBacklightBright:(NSInteger)bright;
- (void)bleLanguage:(NSInteger)type;
- (void)bleRecScene:(NSInteger)scene;
- (void)bleRecMode:(NSInteger)mode;
- (void)bleVadSensitivity:(NSInteger)value;
- (void)bleVpuGain:(NSInteger)value;
- (void)bleSwitchHandler:(NSInteger)id;
- (void)bleAutoPowerOff:(NSInteger)value;
- (void)bleRawWaveEnabled:(NSInteger)value;
- (void)bleRecordingAfterDisConnetEnabled:(NSInteger)value;
- (void)bleFindMyState:(NSInteger)value;
- (void)bleVPUCLKState:(NSInteger)value;
- (void)bleStopRecordingAfterCharging:(NSInteger)value;
- (void)bleAutoClear:(BOOL)open;
- (void)bleVad:(BOOL)open;
- (void)bleWiFiClose:(NSInteger)status;
- (void)bleSetWiFiSsidWithStatus:(NSInteger)status;
- (void)bleGetWiFiSsidWithStatus:(NSInteger)status ssid:(NSString * _Nullable)ssid;
- (void)bleVoiceAbnormalWithStatus:(NSInteger)status;
- (void)bleWebsocketProfile:(NSInteger)type :(NSString * _Nullable)conent;
- (void)bleWebsocketTest:(NSInteger)status;
- (void)bleLedStateOnOff:(NSInteger)onOff;
- (void)bleSetLedStateOnOff:(NSInteger)onOff;
- (void)bleMarkingWithSessionId:(NSInteger)sessionId status:(NSInteger)status markList:(NSArray<NSNumber *> * _Nonnull)markList;
- (void)bleAnglesWithPitchAngle:(float)pitchAngle rollbackAngle:(float)rollbackAngle yawAngle:(float)yawAngle;
- (void)blePrivacyWithPrivacy:(NSInteger)privacy;
- (void)bleClearAllFileWithStatus:(NSInteger)status;
- (void)bleAlarmRecWithStart:(NSInteger)start duration:(NSInteger)duration repeatMode:(NSInteger)repeatMode;
- (void)onResetFindmyResultWithResult:(NSInteger)result;
- (void)onCommonParamsSetResultWithSuccess:(BOOL)success dataType:(NSInteger)dataType value:(NSString * _Nullable)value;
- (void)onCommonParamsGetResultWithSuccess:(BOOL)success dataType:(NSInteger)dataType value:(NSString * _Nullable)value;
- (void)onSetSoundPlusTokenResultWithLicenseKey:(NSString * _Nonnull)licenseKey;
- (void)onGetSDFlashCIDResultWithCid:(NSString * _Nonnull)cid;
@end


SWIFT_PROTOCOL("_TtP19PlaudDeviceBasicSDK24PlaudDeviceAgentProtocol_")
@protocol PlaudDeviceAgentProtocol
@optional
/// AppKey verification result
/// \param result Verification result 0 temporary 1 success 2 failure
///
- (void)bleAppKeyStateWithResult:(NSInteger)result;
@required
/// Return status
/// \param state Customized according to project (4099(0x00001003) indicates recorder is recording, 1 seems to be recording)
///
/// \param privacy Privacy setting status
///
/// \param keySatte Toggle switch status (new in protocol version 4)
///
/// \param uDisk Whether U disk is enabled
/// Other two parameters are directly placed in BleAgent
///
/// \param scene Current recording scene (0 when not recording)
///
/// \param findMyToken Whether findmy token exists (NotePin device)
///
/// \param hasSndpKey Whether sound plus license token exists
///
/// \param deviceAccessToken Whether device idle sync AccessToken exists
///
/// \param sessionId Current session id (0 when not recording)
///
- (void)blePenStateWithState:(NSInteger)state privacy:(NSInteger)privacy keyState:(NSInteger)keyState uDisk:(NSInteger)uDisk findMyToken:(NSInteger)findMyToken hasSndpKey:(NSInteger)hasSndpKey deviceAccessToken:(NSInteger)deviceAccessToken;
@optional
/// Device name
/// \param name Device name
///
- (void)bleDeviceNameWithName:(NSString * _Nullable)name;
/// Bluetooth device scan callback
/// \param bleDevices Bluetooth device list
///
- (void)bleScanResultWithBleDevices:(NSArray<BleDevice *> * _Nonnull)bleDevices;
/// Scan timeout end
/// @see startScan
- (void)bleScanOverTime;
/// Bluetooth connection status
/// <ul>
///   <li>
///     Parameters state: 0 disconnected or not connected; 1 connection successful; 2 connection failed
///   </li>
/// </ul>
- (void)bleConnectStateWithState:(NSInteger)state;
/// Bluetooth connection stage (diagnostics)
/// \param sn device serial number (may be nil before it is known)
///
/// \param stage start / gatt_connect / set_notify / set_battery_notify / read_battery / set_data_notify /
/// pre_handshake / send_rsa_public / first_handshake / two_handshake / handshake_get_ssn /
/// change_handshake_timeout / sync_time
///
/// \param detail stage detail or failure reason, e.g. sn_signature_empty / sn_signature_invalid /
/// user_rsa_public_key_empty / bind_token_empty / ok / status_1 (1 = token mismatch)
///
- (void)bleConnectStageWithSn:(NSString * _Nullable)sn stage:(NSString * _Nonnull)stage detail:(NSString * _Nullable)detail;
/// Connection callback
/// \param status Status, 0: success, >0: rejected 1: Token mismatch 2: Screen project, currently recording, user cannot confirm temporarily 3: Screen project, user manually rejected 255: Recorder not in connection mode, reject handshake request in non-connection mode (unique to Heili three-stage switch) <0 verification failed -1: no SSN -2: network exception -3: server data exception or verification incorrect
///
/// \param protVersion Protocol version number
///
/// \param timezone Current timezone on pen side
///
- (void)bleBindWithSn:(NSString * _Nullable)sn status:(NSInteger)status protVersion:(NSInteger)protVersion timezone:(NSInteger)timezone;
/// Microphone sensitivity
/// \param value 1- 30
///
- (void)bleMicGain:(NSInteger)value;
/// Device space
/// \param total Total space size (bytes)
///
/// \param free Remaining space size (bytes)
///
/// \param duration Recorder’s estimated remaining recording duration (milliseconds)
///
- (void)bleStorageWithTotal:(NSInteger)total free:(NSInteger)free duration:(NSInteger)duration;
/// Battery level change
/// \param power Current battery level
///
/// \param oldPower Previous battery level (used to determine low battery reminders from 20%->19% and 10%->9%)
///
- (void)blePowerChangeWithPower:(NSInteger)power oldPower:(NSInteger)oldPower;
/// Battery level status
/// \param isCharging Whether charger is plugged in 0 not plugged in 1 plugged in (BleDevice has an isCharging property that will be set after this callback, can compare previous value to determine charging status change)
///
/// \param level Battery level 0-100
///
- (void)bleChargingStateWithIsCharging:(BOOL)isCharging level:(NSInteger)level;
/// Get file list callback
/// \param bleFiles File list
///
- (void)bleFileListWithBleFiles:(NSArray<BleFile *> * _Nonnull)bleFiles;
/// Start recording callback
/// \param sessionId Recording file unique id, 0 timezone timestamp, to convert to phone current timestamp need to subtract timezone
///
/// \param start Recorded duration (file offset, bytes) (returns 0 if not recording before; if recording before, returns recorded duration)
///
/// \param status 0: success, >0: failure 1: space full; 2: U disk mode; 3: hardware exception; 4: currently busy; 255: wrong mode (recorder not in recording mode, unique to Heili three-stage switch)
///
/// \param scene Recording mode
///
/// \param startTime Start time
///
- (void)bleRecordStartWithSessionId:(NSInteger)sessionId start:(NSInteger)start status:(NSInteger)status scene:(NSInteger)scene startTime:(NSInteger)startTime reason:(NSInteger)reason;
/// End recording callback
/// \param sessionId Recording file unique id, 0 timezone timestamp, to convert to phone current timestamp need to subtract timezone
///
/// \param reason Reason (others undefined)
/// 1.MMI_REC_STOP_FROM_DEV    /// Device side stop recording
/// 2.MMI_REC_STOP_FROM_APP    /// APP side stop recording
/// 3.MMI_REC_STOP_BY_SPLIT        /// Automatic time slice stop recording
/// 4.MMI_REC_STOP_BY_SWITCH   ///  Switch toggle stop recording)
///
/// \param fileExist Whether file is saved
///
/// \param fileSize File size (if available, bytes)
///
- (void)bleRecordStopWithSessionId:(NSInteger)sessionId reason:(NSInteger)reason fileExist:(BOOL)fileExist fileSize:(NSInteger)fileSize;
/// Recording pause callback
/// \param sessionId Recording file unique id, 0 timezone timestamp, to convert to phone current timestamp need to subtract timezone
///
/// \param reason Reason (currently undefined)
///
/// \param fileExist Whether file is saved
///
/// \param fileSize File size (if available, bytes)
///
- (void)bleRecordPauseWithSessionId:(NSInteger)sessionId reason:(NSInteger)reason fileExist:(BOOL)fileExist fileSize:(NSInteger)fileSize;
/// Recording resume
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     sessionId: Recording file unique id, 0 timezone timestamp, to convert to phone current timestamp need to subtract timezone
///   </li>
///   <li>
///     start: Recorded duration (file offset, bytes) (returns 0 if not recording before; if recording before, returns recorded duration)
///   </li>
///   <li>
///     status: 0: success, >0: failure 1: space full; 2: U disk mode; 3: hardware exception
///   </li>
///   <li>
///     scene: Recording mode (depends on project, version number)
///   </li>
///   <li>
///     startTime: Start time (depends on project, version number)
///   </li>
/// </ul>
- (void)bleRecordResumeWithSessionId:(NSInteger)sessionId start:(NSInteger)start status:(NSInteger)status scene:(NSInteger)scene startTime:(NSInteger)startTime;
/// Sync (download) file start callback
/// \param sessionId File unique id
///
/// \param status Status, 0: success; >0: failure 1: file system currently unavailable 2: file does not exist 3: interrupted
///
- (void)bleSyncFileHeadWithSessionId:(NSInteger)sessionId status:(NSInteger)status;
/// Sync (download) file end
/// \param sessionId File unique id
///
/// \param crc File checksum code, verify file integrity (don’t use after recorder changed to egg file saving)
///
- (void)bleSyncFileTailWithSessionId:(NSInteger)sessionId crc:(NSInteger)crc;
/// Voice data return
/// \param sessionId File id, protocol 7 support
///
/// \param start Data offset in undecoded file (bytes)
///
/// \param data Data (may be ogg data or opus pure audio, determined by firmware)
///
- (void)bleDataWithSessionId:(NSInteger)sessionId start:(NSInteger)start data:(NSData * _Nonnull)data;
/// Return decoded pcm data
/// \param sessionId File id, protocol 7 support
///
/// \param millsec Current voice millisecond value
///
/// \param pcmData Decoded data, will not callback if decoding not required when starting recording; if recording is dual channel, will process to single channel; music mode is dual channel 48k sampling rate, will process to single channel 48k, not usable for recognition
///
/// \param isMusic Is it music mode? Music mode returned pcm is not normal pcm, is 6 shorts take one, used to generate waveform, cannot be used for recognition
///
- (void)blePcmDataWithSessionId:(NSInteger)sessionId millsec:(NSInteger)millsec pcmData:(NSData * _Nonnull)pcmData isMusic:(BOOL)isMusic;
/// Data reception completed
- (void)bleDataComplete;
/// Voice data decoding failed
/// \param start Data offset in undecoded file
///
- (void)bleDecodeFailWithStart:(NSInteger)start;
/// Sync file terminated
- (void)bleSyncFileStop;
/// Sync composite file callback
/// \param sessionId File unique id
///
/// \param sessionId Output file path
///
/// \param status 0 normal -1 error
///
/// \param progress Progress 0-100
///
/// \param tips Tips
///
- (void)bleDownloadFileWithSessionId:(NSInteger)sessionId desiredOutputPath:(NSString * _Nonnull)desiredOutputPath status:(NSInteger)status progress:(NSInteger)progress tips:(NSString * _Nonnull)tips;
/// Sync file terminated
- (void)bleDownloadFileStop;
/// Delete file
/// \param sessionId Protocol version 7 support
///
/// \param status Status, 0: delete successful; 1: recording not allowed to delete 2: favorited not allowed to delete; 3: playing not allowed to delete
///
- (void)bleDeleteFileWithSessionId:(NSInteger)sessionId status:(NSInteger)status;
/// Unbind
/// \param status 0 success; 1 working 2 upgrading
///
- (void)bleDepair:(NSInteger)status;
- (void)onWifiSyncConfigReceivedWithIndex:(uint32_t)index ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password;
/// Set idle sync WiFi configuration result
/// \param result Result code (0: success, 1: already exists, 2: device not found for deletion, 3: change not found, 4: operation code exception, 5: queue full, other: other errors)
///
- (void)onWifiSyncConfigSetWithResult:(NSInteger)result;
/// Idle sync WiFi list reception
/// \param list WiFi index list
///
- (void)onWifiSyncListReceivedWithList:(NSArray<NSNumber *> * _Nonnull)list;
/// Idle sync WiFi delete result
/// \param result Result code (0: success, -1: failure)
///
- (void)onWifiSyncDeleteResultWithResult:(NSInteger)result;
/// Idle sync WiFi test start
/// \param index WiFi number
///
- (void)onWifiSyncTestStartedWithIndex:(uint32_t)index;
/// Idle sync about to start
/// \param second Seconds until start
///
- (void)onWifiSyncWillStartWithSeconds:(NSInteger)seconds;
/// Idle sync WiFi test result
/// \param index WiFi number
///
/// \param result Test result: 0, test successful 1, wifi not found 2, Wifi password incorrect 3, Wifi connection failed 4, data transmission failed
///
/// \param rawCode Original error code
///
- (void)onWifiSyncTestResultWithIndex:(uint32_t)index result:(NSInteger)result rawCode:(NSInteger)rawCode;
- (void)onWifiSyncUrlWithUrl:(NSString * _Nonnull)url;
/// WiFi RSSI measurement request confirmed
/// \param status Status code (0: success, other: error)
///
- (void)onWifiRssiRequestConfirmedWithStatus:(NSInteger)status;
- (void)onSdkFetchPermissionResultWithPass:(BOOL)pass tips:(NSString * _Nonnull)tips;
- (void)onSdkCheckPermissionResultWithPass:(BOOL)pass tips:(NSString * _Nonnull)tips;
- (void)onSdkCheckResourceResultWithPass:(BOOL)pass tips:(NSString * _Nonnull)tips;
/// Idle sync
/// \param value 0: off 1: on
///
- (void)onWifiSyncEnabled:(NSInteger)value;
- (void)onCommonMsgChannelWithType:(NSInteger)type value:(NSInteger)value tips:(NSString * _Nonnull)tips;
/// WiFi open notification
/// \param status 0 normal, >1 forbidden to open 1 recording status, 2 U disk status
///
/// \param wifiName Recording pen hotspot name
///
/// \param wholeName Determine whether to append 4-digit sn suffix name
///
/// \param wifiPass Recording pen hotspot password
///
- (void)bleWiFiOpen:(NSInteger)status :(NSString * _Nonnull)wifiName :(NSString * _Nonnull)wholeName :(NSString * _Nonnull)wifiPass;
/// OTA notification
/// \param uid Identifier
///
/// \param status Status 0 normal, 1. upgrade failed 2. version information mismatch 3. FLASH write failed 4. file too large 5. too many attempts 6. U disk mode; 7. recording in progress; 8. U disk insufficient remaining space; 9. working; 10. G101 glasses only allow upgrade in charging mode; 11. G101 glasses insufficient battery; 12. G101 glasses received upgrade protocol and preparing to adjust to OTA_MODE; 255: mode incorrect (recording pen not in recording mode, specific to Heili three-way switch)
///
/// \param errmsg Protocol version 4, if upgrade successful, returns upgraded version here; if failed, still returns error message.
///
- (void)bleFotaResultWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
/// OTA package request, recording pen requests to send upgrade package data
/// \param uid Identifier
///
/// \param start Start position (bytes)
///
/// \param end End position (bytes)
///
- (void)bleFotaPackReqWithUid:(NSInteger)uid start:(NSInteger)start end:(NSInteger)end;
/// OTA package reception completed
/// \param uid Identifier
///
/// \param status Status 0 normal, 1. upgrade failed 2. version information mismatch 3. FLASH write failed 4. file too large 5. too many attempts 6. U disk mode; 7. recording in progress; 8. U disk insufficient remaining space
///
/// \param errmsg Protocol version 4, if upgrade successful, returns upgraded version here; if failed, still returns error message.
///
- (void)bleFotaPackFinWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
/// OTA data send failed
- (void)bleOtaDataSendFail;
/// Wake/sleep setting
/// 0: sleep; 1: wake
- (void)bleSetActiveWithStatus:(NSInteger)status;
- (void)bleCommonSettingWithSetting:(NSInteger)setting;
/// Bluetooth transmission rate callback
/// \param lossRate Packet loss rate
///
/// \param rate Average rate, bytes/S
///
/// \param instantRate Real-time rate
///
- (void)bleRateWithLossRate:(double)lossRate rate:(NSInteger)rate instantRate:(NSInteger)instantRate;
@end

/// 文件下载输出格式
typedef SWIFT_ENUM(NSInteger, PlaudDownloadFormat, open) {
/// PCM 格式 - 原始音频数据，需要知道采样率才能正确播放
  PlaudDownloadFormatPcm = 0,
/// MP3 格式 - 暂不支持
  PlaudDownloadFormatMp3 = 1,
/// WAV 格式（推荐）- 带头信息的 PCM，可直接播放
  PlaudDownloadFormatWav = 2,
};


/// E2EE encryption header for Plaud audio files.
/// The header is 512 bytes and contains encryption metadata.
/// NotePro audio files have two encryption layers:
/// <ol>
///   <li>
///     BLE Transport Layer - ChaCha20-Poly1305 (handled by BleAgent)
///   </li>
///   <li>
///     File Content Layer - RSA encrypted key header + ChaCha20 encrypted data (handled here)
///   </li>
/// </ol>
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK18PlaudEncryptHeader")
@interface PlaudEncryptHeader : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger headerSize;)
+ (NSInteger)headerSize SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull magicString;)
+ (NSString * _Nonnull)magicString SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSData * _Nonnull magic;
@property (nonatomic, readonly) uint16_t version;
@property (nonatomic, readonly) uint16_t headerSizeValue;
@property (nonatomic, readonly) uint32_t crc;
@property (nonatomic, readonly, copy) NSData * _Nonnull userId;
@property (nonatomic, readonly) uint16_t fileType;
@property (nonatomic, readonly) uint16_t channel;
@property (nonatomic, readonly) uint16_t encryptType;
@property (nonatomic, readonly) uint32_t duration;
@property (nonatomic, readonly, copy) NSData * _Nonnull reserved;
@property (nonatomic, readonly) uint32_t counter;
@property (nonatomic, readonly, copy) NSData * _Nonnull nonce;
@property (nonatomic, readonly) uint32_t segment;
@property (nonatomic, readonly, copy) NSData * _Nonnull algParams;
@property (nonatomic, readonly, copy) NSData * _Nonnull keyCipher;
/// Parse header from raw data
- (nullable instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
/// Read header from file
+ (PlaudEncryptHeader * _Nullable)fromFileWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
/// Check if the file is encrypted (magic == “PLAUD.AI”)
@property (nonatomic, readonly) BOOL isEncrypted;
/// Get userId as string
@property (nonatomic, readonly, copy) NSString * _Nonnull userIdString;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK17PlaudFileUploader")
@interface PlaudFileUploader : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaudFileUploader * _Nonnull shared;)
+ (PlaudFileUploader * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) BleDevice * _Nullable device;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)uploadRecordingWithSn:(NSString * _Nonnull)sn sessionId:(NSInteger)sessionId duration:(double)duration onProgress:(void (^ _Nonnull)(double))onProgress onSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(NSError * _Nonnull))onFailure;
/// Upload log file
/// \param filePath Path to the log file
///
/// \param sn Device serial number
///
/// \param onProgress Upload progress callback (0.0 to 1.0)
///
/// \param onSuccess Success callback with upload result
///
/// \param onFailure Failure callback with error
///
- (void)uploadLogFileWithFilePath:(NSString * _Nonnull)filePath sn:(NSString * _Nonnull)sn onProgress:(void (^ _Nonnull)(double))onProgress onSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(NSError * _Nonnull))onFailure;
+ (NSString * _Nonnull)calculateSnTypeWithSn:(NSString * _Nonnull)sn SWIFT_WARN_UNUSED_RESULT;
@end


/// 固件版本检查结果
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK24PlaudFirmwareCheckResult")
@interface PlaudFirmwareCheckResult : NSObject
@property (nonatomic, readonly) BOOL hasUpdate;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull latestVersion;
@property (nonatomic, readonly) NSInteger versionCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull releaseNotes;
@property (nonatomic, readonly, copy) NSString * _Nonnull downloadUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull md5;
@property (nonatomic, readonly) BOOL isForce;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 固件升级进度
typedef SWIFT_ENUM(NSInteger, PlaudFirmwarePhase, open) {
  PlaudFirmwarePhaseDownloading = 0,
  PlaudFirmwarePhaseInstalling = 1,
  PlaudFirmwarePhaseRestarting = 2,
  PlaudFirmwarePhaseComplete = 3,
};


/// 固件升级结果
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK25PlaudFirmwareUpdateResult")
@interface PlaudFirmwareUpdateResult : NSObject
@property (nonatomic, readonly) BOOL success;
@property (nonatomic, readonly, copy) NSString * _Nonnull version;
@property (nonatomic, readonly, copy) NSString * _Nullable errorMessage;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Centralized log configuration manager for all Plaud SDK modules
/// Located in PenBleSDK to avoid reverse dependency issues
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK14PlaudLogConfig")
@interface PlaudLogConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaudLogConfig * _Nonnull shared;)
+ (PlaudLogConfig * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Maximum number of log files to keep
@property (nonatomic, readonly) NSInteger maxFileCount;
/// Maximum age of log files in seconds (default: 7 days)
@property (nonatomic, readonly) NSTimeInterval maxFileAge;
/// Maximum size of individual log file in bytes (default: 10MB)
@property (nonatomic, readonly) int64_t maxFileSize;
/// Upload interval in seconds (DEBUG: 1 minute, RELEASE: 5 minutes)
@property (nonatomic, readonly) NSTimeInterval uploadInterval;
/// Upload timeout in seconds (default: 30 seconds)
@property (nonatomic, readonly) NSTimeInterval uploadTimeout;
/// Update log file management configuration
/// \param maxFileCount Maximum number of log files to keep (1-50)
///
/// \param maxFileAge Maximum age of log files in seconds (1 hour - 30 days)
///
/// \param maxFileSize Maximum size of individual log file in bytes (1MB - 100MB)
///
- (void)updateFileConfigurationWithMaxFileCount:(NSInteger)maxFileCount maxFileAge:(NSTimeInterval)maxFileAge maxFileSize:(int64_t)maxFileSize;
/// Update upload configuration
/// \param uploadInterval Upload interval in seconds (60s - 3600s)
///
/// \param uploadTimeout Upload timeout in seconds (10s - 300s)
///
- (void)updateUploadConfigurationWithUploadInterval:(NSTimeInterval)uploadInterval uploadTimeout:(NSTimeInterval)uploadTimeout;
/// Reset configuration to default values
- (void)resetToDefaults;
/// Get current configuration as dictionary
- (NSDictionary<NSString *, id> * _Nonnull)getCurrentConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Get max file age in days
@property (nonatomic, readonly) NSInteger maxFileAgeDays;
/// Get max file size in MB
@property (nonatomic, readonly) NSInteger maxFileSizeMB;
/// Get upload interval in minutes
@property (nonatomic, readonly) NSInteger uploadIntervalMinutes;
/// Get upload timeout in seconds
@property (nonatomic, readonly) NSInteger uploadTimeoutSeconds;
@end


@interface PlaudLogConfig (SWIFT_EXTENSION(PlaudDeviceBasicSDK))
/// Validate current configuration
- (BOOL)validateConfiguration SWIFT_WARN_UNUSED_RESULT;
/// Get configuration description for debugging
- (NSString * _Nonnull)getConfigurationDescription SWIFT_WARN_UNUSED_RESULT;
@end

@class NSURL;

/// 加密日志导出器，生成与 Android SDK 兼容的 .plaud 格式
/// 格式：ChaCha20(ZIP(log files + sdk_info.txt))
SWIFT_CLASS_NAMED("PlaudLogEncryption")
@interface PlaudLogEncryption : NSObject
/// 导出加密日志包（.plaud）。<em>失败时抛出 [PlaudLogExportError]，明确原因</em>，不再静默返回 nil。
/// ObjC 调用：<code>[PlaudLogEncryption exportEncryptedLogFileAndReturnError:&error]</code>，失败看 <code>error.localizedDescription</code>。
+ (NSURL * _Nullable)exportEncryptedLogFileAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
/// 兼容旧接口：失败返回 nil（无原因）。新接入方请改用 <code>exportEncryptedLogFile()</code>。
+ (NSURL * _Nullable)exportEncryptedLogs SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Log file rotation manager
/// Responsible for unified management of log file switching logic, ensuring immediate switch to new file after upload
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK27PlaudLogFileRotationManager")
@interface PlaudLogFileRotationManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaudLogFileRotationManager * _Nonnull shared;)
+ (PlaudLogFileRotationManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Force rotate current log file
/// Usually called after successful upload to ensure subsequent logs are written to new file
- (void)forceRotateCurrentLogFile;
/// Check and perform size-based rotation
/// \param filePath Log file path
///
/// \param additionalSize Size of data to be written
///
///
/// returns:
/// Whether rotation was performed
- (BOOL)checkAndRotateIfNeededWithFilePath:(NSString * _Nonnull)filePath additionalSize:(int64_t)additionalSize SWIFT_WARN_UNUSED_RESULT;
/// Get current active log file path
- (NSString * _Nonnull)getCurrentLogFilePath SWIFT_WARN_UNUSED_RESULT;
/// Notify manager that upload is completed, suggest file rotation
- (void)notifyUploadCompleted;
@end

typedef SWIFT_ENUM(NSInteger, PlaudLogUploadError, open) {
  PlaudLogUploadErrorAlreadyUploading = 0,
  PlaudLogUploadErrorDirectoryNotFound = 1,
  PlaudLogUploadErrorPartialUpload = 2,
};
static NSString * _Nonnull const PlaudLogUploadErrorDomain = @"PlaudDeviceBasicSDK.PlaudLogUploadError";


/// Log upload manager for automatic periodic upload and management
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK21PlaudLogUploadManager")
@interface PlaudLogUploadManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaudLogUploadManager * _Nonnull shared;)
+ (PlaudLogUploadManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Enable or disable automatic log upload
/// \param enabled true to enable auto upload, false to disable
///
- (void)setAutoUploadEnabled:(BOOL)enabled;
/// Start automatic log upload timer
- (void)startAutoUpload;
/// Stop automatic log upload timer
- (void)stopAutoUpload;
/// Upload log files with progress tracking
/// \param onProgress Progress callback (0.0 to 1.0)
///
/// \param onSuccess Success callback with upload results
///
/// \param onFailure Failure callback with error
///
- (void)uploadLogFilesOnProgress:(void (^ _Nonnull)(double))onProgress onSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(NSError * _Nonnull))onFailure;
/// Manually trigger log cleanup
- (void)cleanupLogFiles;
/// Get upload statistics
///
/// returns:
/// Dictionary with upload statistics
- (NSDictionary<NSString *, id> * _Nonnull)getUploadStatistics SWIFT_WARN_UNUSED_RESULT;
/// Upload log files with specific device serial number
/// \param sn Device serial number
///
/// \param onProgress Progress callback (0.0 to 1.0)
///
/// \param onSuccess Success callback with upload results
///
/// \param onFailure Failure callback with error
///
- (void)uploadLogFilesWithDeviceSNWithSn:(NSString * _Nonnull)sn onProgress:(void (^ _Nonnull)(double))onProgress onSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSuccess onFailure:(void (^ _Nonnull)(NSError * _Nonnull))onFailure;
/// Upload logs after recording upload completion
/// \param sn Device serial number
///
/// \param sessionId Session ID
///
/// \param onCompletion Completion callback
///
- (void)uploadLogsAfterRecordingWithSn:(NSString * _Nonnull)sn sessionId:(NSInteger)sessionId onCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))onCompletion;
@end


/// PCM 文件播放器 - 直接播放 PCM 文件，避免 MP3 转换引入的噪音
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK14PlaudPCMPlayer")
@interface PlaudPCMPlayer : NSObject
@property (nonatomic, readonly) BOOL isPlaying;
@property (nonatomic, readonly) BOOL isPaused;
@property (nonatomic, readonly) NSTimeInterval duration;
@property (nonatomic, readonly) NSTimeInterval currentTime;
@property (nonatomic, copy) void (^ _Nullable onPlaybackFinished)(void);
@property (nonatomic, copy) void (^ _Nullable onError)(NSString * _Nonnull);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 加载 PCM 文件
- (BOOL)loadFileWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
/// 播放
- (void)play;
/// 暂停
- (void)pause;
/// 停止
- (void)stop;
@end


SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK14PlaudSDKLogger")
@interface PlaudSDKLogger : NSObject
+ (void)logEvent:(NSString * _Nonnull)eventName parameters:(NSDictionary * _Nullable)parameters;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol PlaudWiFiAgentProtocol;

SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK14PlaudWiFiAgent")
@interface PlaudWiFiAgent : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaudWiFiAgent * _Nonnull shared;)
+ (PlaudWiFiAgent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <PlaudWiFiAgentProtocol> _Nullable delegate;
/// Device information needs to be passed from Bluetooth module
@property (nonatomic, strong) BleDevice * _Nullable bleDevice;
/// Whether currently downloading file
@property (nonatomic, readonly) BOOL isDownloading;
/// Current sync file sessionId
@property (nonatomic, readonly) NSInteger currentSessionId;
/// Whether connection has been established
@property (nonatomic, readonly) BOOL isConnected;
/// Get current download speed (KB/s)
@property (nonatomic, readonly) double currentDownloadSpeedKBps;
/// Get formatted download speed string
- (NSString * _Nonnull)getFormattedDownloadSpeed SWIFT_WARN_UNUSED_RESULT;
/// Whether currently batch downloading
@property (nonatomic, readonly) BOOL isDownloadingAll;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Enable SDK debug logs or callback logs
- (void)openLog:(BOOL)opened :(void (^ _Nullable)(NSString * _Nonnull))backBlock;
/// Use this method for iOS 11.0 and below, will loop to check if connected to specified WiFi until timeout
/// \param ssid WiFi name
///
/// \param overtimeSec Timeout duration, default 30 seconds
///
- (void)listenPort:(NSString * _Nonnull)ssid :(NSInteger)overtimeSec;
- (void)connectWifi:(NSString * _Nonnull)ssid :(NSString * _Nonnull)passphrase :(NSInteger)overtimeSec;
/// Disconnect
- (void)disconnect;
/// Check if currently connected to specified WiFi
/// \param ssid WiFi name
///
///
/// returns:
/// Whether connected
- (BOOL)isConnectedTo:(NSString * _Nonnull)ssid SWIFT_WARN_UNUSED_RESULT;
/// Get current connection status description
///
/// returns:
/// Connection status description
- (NSString * _Nonnull)getConnectionStatusDescription SWIFT_WARN_UNUSED_RESULT;
/// Get current connected WiFi name
- (NSString * _Nullable)getCurrentWiFiName SWIFT_WARN_UNUSED_RESULT;
/// Get file list (app initiated cmd=11)
/// \param uid Request uid, new requests will naturally override old requests
///
/// \param sessionId Starting sessionId
///
/// \param single Whether to only get current file information, default false
///
- (void)getFileList:(NSInteger)uid :(NSInteger)sessionId :(BOOL)single;
/// File sync (cmd=12)
/// \param sessionId Recording ID
///
/// \param start Start position (file offset, not time)
///
/// \param end End position (default 0, to end of file)
///
/// \param scene Recording scene, default 1
///
- (void)syncFile:(NSInteger)sessionId :(NSInteger)start :(NSInteger)end :(NSInteger)scene;
/// Stop file sync (cmd=15)
/// \param sessionId Recording ID
///
/// \param scene Scene, default 1
///
- (void)stopSyncFile:(NSInteger)sessionId :(NSInteger)scene;
/// Delete file (cmd=14)
/// \param sessionId Recording ID
///
/// \param scene Scene, default 1
///
- (void)deleteFile:(NSInteger)sessionId :(NSInteger)scene;
/// 批量下载全部文件(命名对齐 Android <code>getWifiAgent().downloadAllFiles()</code>)。等价于 <code>startDownloadAll()</code>。
/// 进度走 <code>wifiDownloadAllProgress</code>，完成走 <code>wifiDownloadAllCompleted</code>。
- (void)downloadAllFiles;
/// Start downloading all files
/// First get file list, then download one by one
- (void)startDownloadAll;
/// Stop downloading all files
- (void)stopDownloadAll;
/// Rate test (cmd=100)
/// \param onOff Start or end
///
/// \param packSize Test package size
///
- (void)startRateTest:(BOOL)onOff :(NSInteger)packSize;
/// Pen-side log retrieval (cmd=101)
/// \param begin Start or end
///
- (void)getDeviceLogs:(BOOL)begin;
/// Whether WebSocket connection has been successfully established (prerequisite for app to send requests)
- (BOOL)isWebSocketConnected SWIFT_WARN_UNUSED_RESULT;
@end


@interface PlaudWiFiAgent (SWIFT_EXTENSION(PlaudDeviceBasicSDK)) <WiFiAgentProtocol>
- (void)wifiCommonErr:(NSInteger)cmd :(NSInteger)status;
- (void)wifiHandshake:(NSInteger)status;
- (void)wifiPower:(NSInteger)power :(NSInteger)voltage;
- (void)wifiFileListFail:(NSInteger)status;
- (void)wifiFileList:(NSArray<BleFile *> * _Nonnull)files;
- (void)wifiSyncFile:(NSInteger)sessionId :(NSInteger)status;
- (void)wifiSyncFileData:(NSInteger)sessionId :(NSInteger)offset :(NSInteger)count :(NSData * _Nonnull)binData;
- (void)wifiDataComplete;
- (void)wifiSyncFileStop:(NSInteger)status;
- (void)wifiFileDelete:(NSInteger)sessionId :(NSInteger)status;
- (void)wifiClientFail;
- (void)wifiClose:(NSInteger)status;
- (void)wifiRateFail:(NSInteger)status;
- (void)wifiRate:(NSInteger)instantRate :(NSInteger)averageRate :(double)lossRate;
- (void)wifiLogsFail:(NSInteger)status;
- (void)wifiLogs:(NSData * _Nullable)logData;
- (void)wifiTips:(NSInteger)tips;
- (void)penRequestOTADataWithStart:(NSInteger)start end:(NSInteger)end payloadSize:(NSInteger)payloadSize uid:(NSInteger)uid sendRatePPS:(NSInteger)sendRatePPS;
- (void)wifiOTAStatus:(NSInteger)status :(NSInteger)uid;
@end


SWIFT_PROTOCOL("_TtP19PlaudDeviceBasicSDK22PlaudWiFiAgentProtocol_")
@protocol PlaudWiFiAgentProtocol
@optional
/// Common error
/// \param cmd Error command
///
/// \param status Error code
///
- (void)wifiCommonErr:(NSInteger)cmd :(NSInteger)status;
/// Handshake result
/// \param status 0 success, others failure
///
- (void)wifiHandshake:(NSInteger)status;
/// WiFi connection status change
/// \param ssid WiFi name
///
/// \param connected Whether connection succeeded
///
- (void)wifiConnectionStatus:(NSString * _Nonnull)ssid :(BOOL)connected;
/// 加入设备热点(NEHotspotConfigurationManager)的结果。
/// 失败时给出<em>明确原因</em>(对标接入方诉求)：errorCode 为 NEHotspotConfigurationError 原始码
/// (如 invalidWPAKey 密码错 / userDenied 被拒 / alreadyAssociated 已连接 等)，message 为可读说明。
/// \param success 是否加入成功
///
/// \param errorCode 失败时的 NEHotspotConfigurationError 原始码(成功为 0)
///
/// \param message 可读原因(成功为空串)
///
- (void)wifiConnectResult:(BOOL)success :(NSInteger)errorCode :(NSString * _Nonnull)message;
/// Battery level and voltage
/// \param power Battery level, percentage
///
/// \param voltage Battery voltage, mv
///
- (void)wifiPower:(NSInteger)power :(NSInteger)voltage;
/// Failed to get recording list
/// \param status Error code
///
- (void)wifiFileListFail:(NSInteger)status;
/// Get recording list
/// \param files Recording list
///
- (void)wifiFileList:(NSArray<BleFile *> * _Nonnull)files;
/// File sync–file status
/// \param sessionId Recording ID
///
/// \param status Status
///
- (void)wifiSyncFile:(NSInteger)sessionId :(NSInteger)status;
/// File sync–file data
/// \param sessionId Recording ID
///
/// \param offset File offset (bytes)
///
/// \param count File length (bytes)
///
/// \param binData Data
///
- (void)wifiSyncFileData:(NSInteger)sessionId :(NSInteger)offset :(NSInteger)count :(NSData * _Nonnull)binData;
/// A file download completed
- (void)wifiDataComplete;
/// File sync stop
/// \param status Status 0 success
///
- (void)wifiSyncFileStop:(NSInteger)status;
/// File deletion result
/// \param sessionId Recording ID
///
/// \param status Deletion result 0 success, >0 failure reason
///
- (void)wifiFileDelete:(NSInteger)sessionId :(NSInteger)status;
/// Client exception disconnect, waiting for reconnection
/// Please set BleAgent.shared.setWiFiState(false)
- (void)wifiClientFail;
/// WiFi close notification
/// \param status Status -1 is didFailWithError; -2 is timeout not connected; -3 NEHotspotConfigurationManager direct connection exception
///
- (void)wifiClose:(NSInteger)status;
/// Rate test failed
/// \param status Error code
///
- (void)wifiRateFail:(NSInteger)status;
/// Rate test
/// \param instantRate Instantaneous rate
///
/// \param averageRate Average rate
///
/// \param lossRate Packet loss rate
///
- (void)wifiRate:(NSInteger)instantRate :(NSInteger)averageRate :(double)lossRate;
/// Failed to get pen-side logs
/// \param status Error code
///
- (void)wifiLogsFail:(NSInteger)status;
/// Pen-side logs
/// \param logData Log data
///
- (void)wifiLogs:(NSData * _Nullable)logData;
/// Pen sends tips to app
/// \param tips 0 no tip, 1 pen recording key pressed
///
- (void)wifiTips:(NSInteger)tips;
/// Batch download progress callback
/// \param totalFiles Total number of files
///
/// \param currentFileIndex Current file index (starting from 1)
///
/// \param currentFile Currently downloading file
///
/// \param totalProgress Overall download progress (0.0-1.0)
///
- (void)wifiDownloadAllProgress:(NSInteger)totalFiles :(NSInteger)currentFileIndex :(BleFile * _Nullable)currentFile :(double)totalProgress;
/// Batch download completed
/// \param completedFiles Number of completed files
///
/// \param failedFiles Number of failed files
///
- (void)wifiDownloadAllCompleted:(NSInteger)completedFiles :(NSInteger)failedFiles;
@end


SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK19PlaudWifiAddingPage")
@interface PlaudWifiAddingPage : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK20PlaudWifiSettingPage")
@interface PlaudWifiSettingPage : UIViewController <PlaudDeviceAgentProtocol>
- (void)bleAppKeyStateWithResult:(NSInteger)_;
- (void)onWifiSyncUrlWithUrl:(NSString * _Nonnull)url;
- (void)blePenStateWithState:(NSInteger)_ privacy:(NSInteger)_ keyState:(NSInteger)_ uDisk:(NSInteger)_ findMyToken:(NSInteger)_ hasSndpKey:(NSInteger)_ deviceAccessToken:(NSInteger)_;
- (void)bleConnectStateWithState:(NSInteger)state;
- (void)onWifiSyncEnabled:(NSInteger)value;
- (void)onWifiSyncListReceivedWithList:(NSArray<NSNumber *> * _Nonnull)list;
- (void)onWifiSyncConfigReceivedWithIndex:(uint32_t)index ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password;
- (void)onWifiSyncConfigSetWithResult:(NSInteger)result;
- (void)onWifiSyncDeleteResultWithResult:(NSInteger)_;
- (void)onWifiSyncTestResultWithIndex:(uint32_t)index result:(NSInteger)result rawCode:(NSInteger)_;
/// WiFi RSSI measurement request confirmed callback
- (void)onWifiRssiRequestConfirmedWithStatus:(NSInteger)status;
- (void)viewDidLoad;
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)_ context:(void * _Nullable)_;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;

@interface PlaudWifiSettingPage (SWIFT_EXTENSION(PlaudDeviceBasicSDK)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)_ numberOfRowsInSection:(NSInteger)_ SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)_ heightForRowAtIndexPath:(NSIndexPath * _Nonnull)_ SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


/// // a base class of vc to write bottom view
SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK15PresentBottomVC")
@interface PresentBottomVC : UIViewController
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC19PlaudDeviceBasicSDK9TestAgent")
@interface TestAgent : NSObject
/// Singleton
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TestAgent * _Nonnull shared;)
+ (TestAgent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Whether device is connected (WiFi or Bluetooth)
- (NSString * _Nonnull)testFunc SWIFT_WARN_UNUSED_RESULT;
@end


























@class UIPresentationController;

@interface UIViewController (SWIFT_EXTENSION(PlaudDeviceBasicSDK)) <UIViewControllerTransitioningDelegate>
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nullable)presenting sourceViewController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
