//
//  PlaudBleSDK.h
//  PlaudBleSDK
//
//  Copyright © 2025 NiceBuild. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

//! Project version number for PlaudBleSDK.
FOUNDATION_EXPORT double PlaudBleSDKVersionNumber;

//! Project version string for PlaudBleSDK.
FOUNDATION_EXPORT const unsigned char PlaudBleSDKVersionString[];

// ObjC types from the embedded PenBleSDK static library
#import <PlaudBleSDK/JXAvcFilePlayer.h>
#import <PlaudBleSDK/JXOggPlayer.h>
#import <PlaudBleSDK/JXOpusDecoder.h>
#import <PlaudBleSDK/Mp3Convert.h>
#import <PlaudBleSDK/OggUtil.h>
#import <PlaudBleSDK/Transcode.h>
#import <PlaudBleSDK/NsAgcUtil.h>
#import <PlaudBleSDK/PlaudAlgoTool.h>
#import <PlaudBleSDK/SwiftyRSA.h>
#import <PlaudBleSDK/NSData+SHA.h>

// PlaudBleSDK-Swift.h is auto-generated by Xcode (all Swift @objc types are
// compiled directly into this framework — no separate PenBleSDK module needed).
#if __has_include(<PlaudBleSDK/PlaudBleSDK-Swift.h>)
#import <PlaudBleSDK/PlaudBleSDK-Swift.h>
#endif
