#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef PLAUDBLESDK_SWIFT_H
#define PLAUDBLESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreBluetooth;
@import CoreFoundation;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
@import Security;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PlaudBleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class BleDevice;
@protocol BleAgentProtocol;
@protocol GlassProtocol;
@class NSString;
@class NSData;
@class NSNumber;
@class UpdateInfo;

/// 蓝牙传输控制类
SWIFT_CLASS("_TtC11PlaudBleSDK8BleAgent")
@interface BleAgent : NSObject
/// 单例
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BleAgent * _Nonnull shared;)
+ (BleAgent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 封装的录音笔实体类
@property (nonatomic, strong) BleDevice * _Nullable bleDevice;
@property (nonatomic, weak) id <BleAgentProtocol> _Nullable delegate;
@property (nonatomic, weak) id <GlassProtocol> _Nullable glassDelegate;
/// 蓝牙是否可用
@property (nonatomic, readonly) BOOL isPoweredOn;
/// 是否已连接设备
@property (nonatomic, readonly) BOOL isConnected;
/// 是否已绑定设备
@property (nonatomic, readonly) BOOL isBinded;
/// 同步文件列表是否仅获取单个文件
@property (nonatomic, readonly) BOOL isOnlyOne;
/// 是否正在录音
@property (nonatomic, readonly) BOOL isRecording;
/// 是否需要解码数据流
@property (nonatomic, readonly) BOOL needDecode;
/// 实时录音的场景是不是音乐模式？
@property (nonatomic, readonly) BOOL isMusic;
/// 当前录音的场景
@property (nonatomic, readonly) NSInteger scene;
@property (nonatomic, readonly) NSInteger settingScene;
/// 当前录音文件或同步（下载）文件的sessionId
@property (nonatomic, readonly) NSInteger sessionId;
/// 是否正在同步（下载）文件
@property (nonatomic, readonly) BOOL isDownloading;
/// 是否是切换WiFi导致的蓝牙断开
@property (nonatomic, readonly) BOOL isWiFiOpen;
/// 重复命令间隔，默认500ms
/// getFileList、syncFile、deleteFile三个命令特殊处理，加入sessionId和start来判断是否是重复命令
@property (nonatomic) NSInteger repeatCommondInterval;
/// 命令回调线程，默认是主线程
@property (nonatomic, strong) dispatch_queue_t _Nonnull cmdDelegateQueue;
/// 8e0b1ef62e607u38ad8200163e02394b    acb89eea1e6011e8ad8200163e02394b
/// 是不是处于U盘模式？
@property (nonatomic) BOOL isUsbState;
@property (nonatomic) BOOL isCharging;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull flutterMapData;
/// 密文包
@property (nonatomic, copy) NSArray<NSData *> * _Nonnull secretPackages;
/// 密文包索引
@property (nonatomic) NSInteger secretIndex;
/// 密文包数量
@property (nonatomic) NSInteger secretCount;
/// 密钥
@property (nonatomic, copy) NSData * _Nullable chacha20Key;
/// 随机数
@property (nonatomic, copy) NSData * _Nullable chacha20Nonce;
/// 认证数据
@property (nonatomic, copy) NSData * _Nullable chacha20AD;
/// WiFi 加密是否使用 AES-GCM（通过 newFeature 协商）
@property (nonatomic) BOOL wifiUseAes;
/// 全局发送给设备的序号
@property (nonatomic) NSInteger globalSendSeq;
/// 全局发送给设备的序号
@property (nonatomic) NSInteger globalReceiveSeq;
@property (nonatomic, copy) NSString * _Nonnull versionType;
@property (nonatomic) NSInteger versionCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// WiFi传输是否打开？没有WiFi模块的不用关心
/// \param connected 是否连接上了
///
- (void)setWiFiState:(BOOL)connected;
/// 用户认证初始化（必须调用）
/// \param appKey 跟包名绑定的key
///
/// \param bindToken 用于绑定录音笔，应该是账号唯一，建议使用服务器发下的openid
///
/// \param hkServer 是否使用HK服务器
/// @see 回调见 bleAppKeyState、
///
- (void)setUserIdentifier:(NSString * _Nonnull)appKey :(NSString * _Nonnull)bindToken :(BOOL)hkServer;
/// 初始化蓝牙，使用蓝牙相关接口之前调用（必须调用）
- (void)initBluetooth SWIFT_METHOD_FAMILY(none);
/// 会先断开连接然后centralManager置nil
- (void)disInitBluetooth;
/// 校验AppKey，第一次校验需要使用网络
/// 该方法建议在AppDelegate中调用，校验成功才能时候后续功能
/// \param appKey 跟包名绑定的key
/// @see        bleAppKeyState
/// @deprecated     该方法废弃，由 setUserIdentifier()方法代替
/// @note       Flutter 路径使用 setUserIdentifier() 初始化，此方法不会被调用。
///
- (void)checkAppKey:(NSString * _Nonnull)appKey;
/// 设置绑定录音笔的token
/// token应该是账号唯一的，不会失效，最好是由服务器统一生成
/// \param token 
/// @deprecated     该方法废弃，由 setUserIdentifier()方法代替
/// @note           Flutter 路径使用 setUserIdentifier() 初始化，此方法不会被调用。
///
- (void)setBinding:(NSString * _Nonnull)token;
/// 设置扫描时的过滤名称
/// 该方法设置后仅过滤一个蓝牙名称
/// 如果设为nil，将显示所有符合协议的录音笔
/// \param name 蓝牙名称
/// @see    setFilter(_ names: [String])
///
- (void)setFilterWithName:(NSString * _Nullable)name;
/// 同时过滤多个
/// 如果数组为空，将显示所有符合协议的录音笔
/// \param names 蓝牙名称
/// @see    setFilter(name: String)
///
- (void)setFilter:(NSArray<NSString *> * _Nonnull)names;
/// 打开sdk的调试日志，或者回调日志
- (void)openLog:(BOOL)opened logBlock:(void (^ _Nullable)(NSString * _Nonnull))logBlock wlogBlock:(void (^ _Nullable)(NSString * _Nonnull))wlogBlock;
/// 是不是连接着某个设备
/// 蓝牙开着、连接着、绑定着并且bleDevice不为nil
///
/// returns:
/// true or false
- (BOOL)isDeviceConnect SWIFT_WARN_UNUSED_RESULT;
/// 开始扫描
/// @see        startLoopScan()
/// @see        stopScan()
/// @see        回调bleScanResult
- (void)startScan;
/// 开始一个循环扫描
/// 内部会启动一个timer，每12秒扫描一次，直到连接上录音笔；断开连接后会重启timer
/// app应该在在扫描的回调中去连接已绑定的设备
/// @see        startScan()
/// @see        stopScan()
/// @see        回调bleScanResult
/// @deprecated     该方法废弃，不建议使用
- (void)startLoopScan;
/// 结束扫描
/// @see        startLoopScan()
/// @see        startScan()
- (void)stopScan;
/// 连接蓝牙设备
/// 不再支持自动连接，设备的版本号是在扫描的时候获取的，自动连接无法更新版本号，在录音笔升级后会有问题
/// @see startLoopScan
/// \param bleDevice 封装的蓝牙设备
///
/// \param devToken 扫码绑定传过来的笔端token，utf-8转成data后长度是8，非扫码绑定是8个0 （捷通的，其他客户不要传）
///
/// \param userName 用户名（捷通的，其他客户不要传）
/// @see    回调bleConnectState
/// @see    回调bleBind
///
- (void)connectBleDeviceWithBleDevice:(BleDevice * _Nonnull)bleDevice :(NSString * _Nullable)devToken :(NSString * _Nullable)userName :(BOOL)isForceClear;
/// 断开蓝牙连接
- (void)disconnect;
/// 录音笔是不是临时校验的？
- (BOOL)isSNTempChecked SWIFT_WARN_UNUSED_RESULT;
/// 如果之前没有校验成功SN，重复校验
- (void)reCheckSNIfNeed;
/// 主动读取电池电量
/// 这个是读的标准电池电量服务，某些情况下会不准
/// 协议5以后自动改为getChargingState
/// @see    getChargingState
/// @see    回调blePowerChange
/// @see    回调bleChargingState
- (void)readPower;
/// 获取电池电量状态
/// 协议5以后改用这个方法读取电量，readPower也会在协议5以后走这里
/// @see    回调blePowerChange
/// @see    回调bleChargingState
- (void)getChargingState;
/// 读取录音笔状态，返回state和隐私状态
/// @see    回调blePenState
- (void)getState;
/// 取消配对，解绑
/// \param clear 是否同时清空录音笔
///
- (void)depairWithClear:(BOOL)clear;
/// 读取录音笔剩余空间
/// @see    回调bleStorage
- (void)getStorage;
/// 重置笔端密码，用于多按键带屏项目，例如纽曼P23H
/// @see    回调blePasswordReset
- (void)appResetPassword;
/// 读取背光时长
/// 用于带屏非多按键项目 例如P23R1。
/// @see    setBacklightDuration
/// @see    回调bleBacklightDuration
- (void)readBacklightDuration;
/// 设置背光时长
/// 用于带屏非多按键项目 例如P23R1。
/// \param type 时长的枚举 0: 10秒 1：20秒 2： 30秒 4： 始终亮屏
/// @see    readBacklightDuration
/// @see    回调bleBacklightDuration
///
- (void)setBacklightDurationWithType:(NSInteger)type;
/// 读取背光对比度
/// 用于带屏非多按键项目 例如P23R1。
/// @see    setBacklightBright
/// @see    回调bleBacklightBright
- (void)readBacklightBright;
/// 设置背光对比度
/// 用于带屏非多按键项目 例如P23R1。
/// \param type 对比度的枚举 1-6
/// @see    readBacklightBright
/// @see    回调bleBacklightBright
///
- (void)setBacklightBrightWithType:(NSInteger)type;
/// 带屏项目获取录音笔当前语言
/// @see    setLanguage
/// @see    回调bleLanguage
- (void)readLanguage;
/// 带屏项目设置录音笔语言
/// \param type 语言类型 0 简体中文 1 繁体中文 2 英语
/// @see    readLanguage
/// @see    回调bleLanguage
///
- (void)setLanguageWithType:(NSInteger)type;
/// 设置录音场景
/// \param value 0 Unknown; 1 Normal; 2 Interview; 3 Classroom(Speech); 4 Music; 5 Meeting; 6 Memo
///
- (void)setRecSceneWithValue:(NSInteger)value;
/// 获取录音场景
/// @see    回调bleRecScene
- (void)readRecScene;
/// 设置录音模式
/// \param value 1 Normal (正常，非降噪); 2 NC (降噪）
///
- (void)setRecModeWithValue:(NSInteger)value;
/// 获取录音模式
/// @see    bleRecMode
- (void)readRecMode;
/// 设置 VAD 敏感度
/// \param value 0：Quality 1：Low bitrate  2：Normal 3：Aggressive
///
- (void)setVadSensitivityWithSensitivity:(NSInteger)sensitivity;
/// 获取 VAD 敏感度
/// @see    bleVadSensitivity
- (void)readVadSensitivity;
/// 设置 VPU 敏感度
/// \param sensitivity 0：Low 1：Medium 2：High
///
- (void)setVpuGainWithGain:(NSInteger)gain;
/// 获取 VPU 敏感度
/// @see    bleVpuGain
- (void)readVpuGain;
/// 设置麦克风增益
/// \param value 麦克风增益值，范围 0 - 30
///
- (void)setMicGainWithValue:(NSInteger)value;
/// 获取 VPU 敏感度
/// @see    bleVpuGain
- (void)readBatteryMode;
/// 续航模式
/// \param value 0：普通，1：长续航
///
- (void)setBatteryModeWithValue:(NSInteger)value;
/// 获取麦克风增益
/// @see    bleMicGain
- (void)readMicGain;
/// 设置 switch 开关功能
/// \param id：0 通话场景切换；1 录音功能； 2 关机功能 
///
- (void)setSwitchHandlerWithId:(NSInteger)id;
/// 获取 switch 开关功能
/// @see    bleSwitchHandler
- (void)readSwitchHandler;
/// 设置 自动关机
/// \param value：0：关闭 1：立即关机 2：15分钟 3：30分钟 4：1个小时 5：5个小时 
///
- (void)setAutoPowerOffWithValue:(NSInteger)value;
/// 获取 switch 开关功能
/// @see    bleSwitchHandler
- (void)readAutoPowerOff;
/// 设置 是否保存 wav 文件
/// \param value：0：关闭 1：开启 
///
- (void)setRawWaveEnabledWithValue:(NSInteger)value;
/// 获取  wav 文件开关功能
/// @see    bleRawWaveEnabled
- (void)readRawWaveEnabled;
/// 获取  充电器拔出后开始录音 开关
/// @see bleRecordingAfterDisConnetEnabled
- (void)readRecordingAfterDisConnetEnabled;
/// 设置 充电器拔出后开始录音 开关
/// \param value：0：关闭 1：开启 
///
- (void)setRecordingAfterDisConnetEnabledWithValue:(NSInteger)value;
/// 获取  闲时同步 开关
/// @see bleSyncWhenIdleEnabled
- (void)readSyncWhenIdleEnabled;
/// 设置 闲时同步 开关
/// \param value：0：关闭 1：开启 
///
- (void)setSyncWhenIdleEnabledWithValue:(NSInteger)value;
/// 获取 iBeacon 唤醒 APP 开关
/// @see bleIBeaconWakeupEnabled
- (void)readIBeaconWakeupEnabled;
/// 设置 iBeacon 唤醒 APP 开关
/// \param value：0：关闭 1：开启 
///
- (void)setIBeaconWakeupEnabledWithValue:(NSInteger)value;
/// 设置 设备 findmy 状态
/// \param value 
/// 0：未绑定状态 - 关闭广播
/// 1：未绑定状态 - 开启广播
/// 2：绑定状态 - 可被查找
/// 3：绑定状态 - 不可被查找
///
- (void)setFindMyStateWithValue:(NSInteger)value;
/// 获取  设备 findmy 状态
/// @see    bleFindMyState
- (void)readFindMyState;
/// 设置 VPU CLK 矫正
/// \param value 0：关闭 1：开启
/// @see    回调 bleSetVpuCLK
///
- (void)setVPUCLKWithValue:(NSInteger)value;
/// 读取 VPU CLK 矫正
/// @see    回调 bleVpuCLK
- (void)readVPUCLK;
/// 设置充电器插入后自动停止录音
/// \param value 0：关闭 1：开启
/// @see    回调 bleStopRecordingAfterCharging
///
- (void)setStopRecordingAfterChargingWithValue:(NSInteger)value;
/// 读取充电器插入后自动停止录音
/// @see    回调 bleStopRecordingAfterCharging
- (void)readStopRecordingAfterCharging;
/// 设置 ble 名称
/// \param name：设备新名字 
///
- (void)setBleNameWithName:(NSString * _Nonnull)name;
/// 获取设备文件列表
- (void)getDeviceLogListWithLogType:(NSInteger)logType;
/// 开始获取设备文件
- (void)startSyncDeviceLogFileWithLogType:(NSInteger)logType logIndex:(NSInteger)logIndex;
/// 停止获取设备文件列表
- (void)stopSyncDeviceLogFile;
/// 删除设备文件
- (void)deleteDeviceLogFileWithLogType:(NSInteger)logType logIndex:(NSInteger)logIndex;
/// 获取 ble 名称
/// @see    bleName
- (void)readBleName;
/// app端请求开启或者关闭wifi
/// \param open 开启还是关闭
///
/// \param isOTA 是否OTA场景
///
/// \param hotspotPassword 热点密码（8 字节 ASCII），仅 open=true 时下发；为 nil/空/不合法时不附带密码
///
- (void)operateWiFiWithOpen:(BOOL)open isOTA:(BOOL)isOTA hotspotPassword:(NSString * _Nullable)hotspotPassword;
/// 旧版兼容包装：保持 ObjC selector <code>operateWiFiWithOpen:isOTA:</code> 不变，避免破坏已有二进制调用方
- (void)operateWiFiWithOpen:(BOOL)open isOTA:(BOOL)isOTA;
/// 获取记录报表
/// \param uid 区分连续请求
///
- (void)readGlassDataWithUid:(NSInteger)uid;
/// 清空记录报表
- (void)clearGlassData;
/// 获取笔端保存的自动删除录音的状态值
/// @see    saveAutoClear
/// @see    回调bleAutoClear
- (void)readAutoClear;
/// 保存自动清除录音状态
/// 注意：录音笔仅保存该状态，方便账号同步设置状态，同步文件完成后是否删除笔端录音依然是app控制
/// \param status 0 关闭 1 打开
/// @see    readAutoClear
/// @see    回调bleAutoClear
///
- (void)saveAutoClear:(BOOL)open;
/// 开始录音（录音速记）
/// 如果开始录音成功，需要自己去syncFile同步文件
/// 可以通过通过同步文件的偏移量显示实时录音时长
/// \param scene 录音场景 1：会议 2：课堂 3：采访 4：音乐 5：备忘
/// @see    回调bleRecordStart
///
- (void)startRecord:(NSInteger)scene;
/// 结束当前录音
/// @see    回调bleRecordStop
- (void)stopRecord;
/// 暂停录音
/// 如果当前录音处于暂停状态，估计版本7之前通过@see startRecord()恢复录音，之后通过resumeRecord()恢复
/// 录音笔协议7开始需要传sessionId，早期版本忽略
/// @see    回调bleRecordPause
- (void)pauseRecord:(NSInteger)sessionId;
/// 恢复录音
/// 协议版本7开始支持
/// @see 回调bleRecordResume
- (void)resumeRecord:(NSInteger)sessionId;
/// 获取录音笔灯状态
/// @see    setLedState
/// @see    回调bleLedState
- (void)getLedState;
/// 设置录音笔灯状态
/// \param onOff 0 正常；1 关闭
/// @see    getLedState
/// @see    回调bleSetLedState
///
- (void)setLedStateOnOff:(NSInteger)onOff;
/// 获取会话列表（获取某个sessionId之后的文件列表）
/// 该命令在录音状态下不可用
/// 该命令在U盘模式下不可用
/// \param uid 用于区分不同的命令
///
/// \param sessionId 从哪个文件开始同步？0 表示同步所有
///
/// \param onlyOne 如果真，那么只查询此sessionId对应的文件（实时录音结束后获取实时录音文件长度），默认false
/// @see    回调bleFileList
///
- (void)getFileListWithUid:(NSInteger)uid sessionId:(NSInteger)sessionId onlyOne:(BOOL)onlyOne;
/// 同步（下载）文件
/// \param sessionId 录音文件的唯一id
///
/// \param start 录音文件起始位置（字节）
///
/// \param end 同步到哪？一搬传0，表示同步到文件尾（字节）
///
/// \param decode 是否同时返回解码后的数据
/// @see    回调bleSyncFileHead
/// @see    回调bleSyncFileTail
/// @see    回调bleData
/// @see    回调bleDecodeFail
/// @see    回调bleDataComplete
/// @see    回调blePcmData
///
- (void)syncFileWithSessionId:(NSInteger)sessionId start:(NSInteger)start end:(NSInteger)end decode:(BOOL)decode;
/// 结束文件同步（下载）
/// @see    回调bleSyncFileStop
- (void)stopSyncFile;
/// 删除录音笔中的文件
/// \param sessionId 录音文件唯一id
/// @see    回调bleDeleteFile
///
- (void)deleteFileWithSessionId:(NSInteger)sessionId;
/// 获取录音打点数据
/// \param sessionId 会话id
///
- (void)getMarking:(NSInteger)sessionId;
/// 获取录音打点数据(3.0新协议)
/// \param uid 请求uid
///
/// \param startTimestamp 起始时间戳
///
/// \param endTimestamp 结束时间戳
///
- (void)getRecordMarkingTagsWithUid:(NSInteger)uid startTimestamp:(NSInteger)startTimestamp endTimestamp:(NSInteger)endTimestamp;
/// 通知录音笔有版本升级（向后兼容重载，isSilent 默认为 false）
/// \param uid 命令区分标识
///
/// \param fromVersion 现在的版本 T0012 或者 V0012 这样的格式
///
/// \param toVersion 目标版本 T0012 或者 V0012 这样的格式
///
/// \param thirdVersion G101项目，其他填0
///
/// \param fileSize 升级包大小（字节）
///
/// \param crc 校验码
/// @see    回调bleFotaResult
/// @see    回调bleFotaPackReq
///
- (void)pushFotaInfo:(NSInteger)uid :(NSString * _Nonnull)fromVersion :(NSString * _Nonnull)toVersion :(NSInteger)thirdVersion :(NSInteger)fileSize :(NSInteger)crc;
/// 通知录音笔有版本升级（向后兼容重载，isSilent 默认为 false）
/// 目标版本一定要大于原版本
/// \param uid 命令区分标识
///
/// \param fromVersion 原版本
///
/// \param fromVersionType 原版本类型
///
/// \param toVersion 目标版本
///
/// \param toVersionType 目标版本类型
///
/// \param fileSize 升级包大小（字节）
///
/// \param crc 校验码
/// @see    回调bleFotaResult
/// @see    回调bleFotaPackReq
///
- (void)pushFotaInfo:(NSInteger)uid :(NSInteger)fromVersion :(NSString * _Nonnull)fromVersionType :(NSInteger)toVersion :(NSString * _Nonnull)toVersionType :(NSInteger)thirdVersion :(NSInteger)fileSize :(NSInteger)crc;
/// 告知录音笔文件已发送完
/// \param uid 标识，区分命令
///
/// \param status 0 正常结束，1 用户退出  0XFF 未知原因
///
- (void)pushFotaComplete:(NSInteger)uid :(NSInteger)status;
/// 发送ota数据包
/// 不能一个循环就全发了，每个包要等一段时间
/// 不同的手机不同的蓝牙版本，等待时长不一样，这个要实际测
/// 目前我的iphone6是等待
/// \param offset 偏移量（字节）
///
/// \param packData 数据包，注意控制单个数据包大小，不要超过最大长度（不同型号这个值是不一样的，保守的话就80）
///
- (void)pushFotaPack:(NSInteger)offset packData:(NSData * _Nonnull)packData postDelayUs:(NSNumber * _Nullable)postDelayUs;
/// 能不能往不稳定栈里面push数据？
- (BOOL)canSendWithoutResponse SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=11.0);
/// 恢复出厂设置
/// 没有回调
- (void)restoreFactory;
/// 隐私设置
/// 开启时，禁止笔端播放，禁止U盘功能，禁止笔端解除绑定
/// \param onOff 1 开启；0 关闭
/// @see    getState
/// @see    回调blePrivacy
///
- (void)setPrivacyOnOff:(NSInteger)onOff;
/// 清空笔端所有文件
/// @see    回调bleClearAllFile
- (void)clearAllFile;
/// 设备 休眠和唤醒
/// \param onOff 1 唤醒；0 休眠
///
- (void)setDeviceActiveWithStatus:(NSInteger)status;
/// 心跳
/// \param status 0 ping, 1 pong
///
- (void)setHeartBeatWithStatus:(NSInteger)status;
/// WiFi配网
/// \param ssid WiFi名称
///
/// \param password 密码
///
/// \param isTest 是否使用测试环境
///
- (void)setWiFiSsidWithSsid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password isTest:(BOOL)isTest;
/// App请求盒子端当前的配网状态
- (void)getWiFiSsid;
/// 获取固件升级信息
/// \param callback errcode == 0 表示Http成功返回
///
- (void)getUpdateInfo:(void (^ _Nonnull)(NSInteger, UpdateInfo * _Nullable))callback;
/// 设置服务器配置
/// \param type 1 服务器url 2 服务器token 2 设备端token
///
/// \param content url最大63字节；serToken最大16字节；devToken最大16字节
///
- (void)setWebsocketProfileWithType:(NSInteger)type content:(NSString * _Nonnull)content;
/// 获取服务器配置
- (void)getWebsocketProfileWithType:(NSInteger)type;
/// 服务器测试
- (void)testWebsocket;
/// 设置定时录音
/// \param start 定时闹钟开始时间（UTC）；0 表示关闭定时闹钟
///
/// \param duration 持续时长（单位s）
///
/// \param repeatMode 0 once仅一次； 1 daily每天定时； 2 weekly每周定时
///
- (void)setAlarmRecWithStart:(NSInteger)start duration:(NSInteger)duration repeatMode:(NSInteger)repeatMode;
/// 获取定时录音
- (void)getAlarmRec;
/// 发送bin文件信息
/// \param type 文件类型
///
/// \param totalSize 文件总大小
///
- (void)sendBinFileInfoWithType:(NSInteger)type totalSize:(NSInteger)totalSize;
/// 发送bin文件数据
/// \param type 文件类型
///
/// \param packageOffset 包偏移量
///
/// \param packageSize 包大小
///
/// \param data 包数据
///
- (void)sendBinFileDataWithType:(NSInteger)type packageOffset:(NSInteger)packageOffset packageSize:(NSInteger)packageSize data:(NSData * _Nonnull)data;
/// 发送bin文件校验和结果
/// \param type 文件类型
///
/// \param crc 校验和
///
- (void)sendBinFileCheckSumResultWithType:(NSInteger)type crc:(NSInteger)crc;
/// 获取闲时同步 Wi-Fi 配置
/// \param wifiIndex Wi-Fi 编号 (4 bytes)
///
- (void)getSyncInIdleWifiConfigWithWifiIndex:(uint32_t)wifiIndex;
/// 设置闲时同步 Wi-Fi 配置
/// \param operation 操作类型 1: 添加, 2: 变更)
///
/// \param wifiIndex Wi-Fi 编号 (4 bytes)
///
/// \param ssid Wi-Fi SSID
///
/// \param password Wi-Fi 密码
///
- (void)setSyncInIdleWifiConfigWithOperation:(NSInteger)operation wifiIndex:(uint32_t)wifiIndex ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password;
/// 删除闲时同步 Wi-Fi 配置
/// \param wifiIndices 要删除的 Wi-Fi 编号数组 (每个编号为 4 bytes)
///
- (void)deleteSyncInIdleWifiConfigWithWifiIndices:(NSArray<NSNumber *> * _Nonnull)wifiIndices;
/// 重置 findmy 状态
- (void)resetFindmy;
/// 获取闲时同步 Wi-Fi 列表
- (void)getSyncInIdleWifiList;
/// 发起闲时同步 Wi-Fi 测试
/// \param wifiIndex Wi-Fi 编号 (4 bytes)
///
- (void)setSyncInIdleWifiTestWithWifiIndex:(uint32_t)wifiIndex;
/// 获取闲时同步 Wi-Fi 测试结果
/// \param wifiIndex Wi-Fi 编号 (4 bytes)
///
- (void)getSyncInIdleWifiTestResultWithWifiIndex:(uint32_t)wifiIndex;
/// 设置声加 license key
/// \param licenseKey license key 字符串 (如果转换后少于 64 字节，将用 0 补足)
///
- (void)setSoundPlusTokenWithLicenseKey:(NSString * _Nonnull)licenseKey;
/// 通用参数设置
/// \param dataType 字符串类型（1: WiFi上云域名/ip, 2: findmy PPID）
///
/// \param value 字符串内容（UTF-8）
///
- (void)setCommonParamsWithDataType:(NSInteger)dataType value:(NSString * _Nonnull)value;
/// 通用参数读取
/// \param dataType 字符串类型（1: WiFi上云域名/ip, 2: findmy PPID）
///
- (void)getCommonParamsWithDataType:(NSInteger)dataType;
/// 获取设备 SDFLASH CID
- (void)getSDFLASHCID;
/// 返回设备的NewFeature
- (void)getNewFeature:(NSData * _Nonnull)data;
/// 获取设备状态
- (void)getDeviceStatus;
/// 查询设备 OTA 下载进度（cmd 151）
- (void)getSyncOtaFileInfo;
@end



/// pcm流式解码协议
SWIFT_PROTOCOL("_TtP11PlaudBleSDK20JXPcmProcessDelegate_")
@protocol JXPcmProcessDelegate
/// 回调pcm数据
/// \param sessionId 录音id
///
/// \param millSec 当前数据毫秒值（起始时刻毫秒值）
///
/// \param pcmData 纯音频已解码数据，长度是20ms
///
- (void)onPcmData:(NSInteger)sessionId :(NSInteger)millSec :(NSData * _Nonnull)pcmData;
- (void)onDecodeErr:(NSInteger)millSec;
@end


@interface BleAgent (SWIFT_EXTENSION(PlaudBleSDK)) <JXPcmProcessDelegate>
- (void)onPcmData:(NSInteger)sessionId :(NSInteger)millSec :(NSData * _Nonnull)pcmData;
- (void)onDecodeErr:(NSInteger)millSec;
@end



@class CBCentralManager;
@class CBPeripheral;

@interface BleAgent (SWIFT_EXTENSION(PlaudBleSDK)) <CBCentralManagerDelegate>
- (void)centralManager:(CBCentralManager * _Nonnull)central willRestoreState:(NSDictionary<NSString *, id> * _Nonnull)dict;
/// 判断手机蓝牙状态
/// mark - sdk实现系统回调，app不要调用
- (void)centralManagerDidUpdateState:(CBCentralManager * _Nonnull)central;
/// 扫描到外围设备后去连接
/// mark - sdk实现系统回调，app不要调用
- (void)centralManager:(CBCentralManager * _Nonnull)central didDiscoverPeripheral:(CBPeripheral * _Nonnull)peripheral advertisementData:(NSDictionary<NSString *, id> * _Nonnull)advertisementData RSSI:(NSNumber * _Nonnull)RSSI;
/// 连接成功
/// mark - sdk实现系统回调，app不要调用
- (void)centralManager:(CBCentralManager * _Nonnull)central didConnectPeripheral:(CBPeripheral * _Nonnull)peripheral;
/// 连接失败
/// mark - sdk实现系统回调，app不要调用
- (void)centralManager:(CBCentralManager * _Nonnull)central didFailToConnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
/// 断开连接，尝试重连
/// mark - sdk实现系统回调，app不要调用
- (void)centralManager:(CBCentralManager * _Nonnull)central didDisconnectPeripheral:(CBPeripheral * _Nonnull)peripheral error:(NSError * _Nullable)error;
@end

@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface BleAgent (SWIFT_EXTENSION(PlaudBleSDK)) <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
@end




@interface BleAgent (SWIFT_EXTENSION(PlaudBleSDK))
/// 授权是否成功
- (BOOL)isAuthOk SWIFT_WARN_UNUSED_RESULT;
/// 双声道转单声道
/// \param pcmData 一个数据包，大小应该是1280
///
- (NSData * _Nonnull)toSingleChannel:(NSData * _Nonnull)pcmData SWIFT_WARN_UNUSED_RESULT;
@end

@class BleFile;
@class BleRecordMarkingTag;

/// 代理
SWIFT_PROTOCOL("_TtP11PlaudBleSDK16BleAgentProtocol_")
@protocol BleAgentProtocol
/// 升级时电量不足（
/// 在pushFotaInfo的时候检查（电量在40以下不允许升级）
- (void)bleUpdatePowerLowErr;
/// 未连接设备
/// 发送命令前都会检查是不是正常连着设备
- (void)bleDeviceDisconnectErr;
/// 当录音笔处于U盘模式，调用getFileList/startRecord/syncFile/deleteFile/pushFotaInfo等方法时回调此异常
/// 录音笔初次连接，需要app调用getState获取录音笔状态
/// \param funcName U盘模式下不支持的方法名
///
- (void)bleUDiskErrWithFuncName:(NSString * _Nonnull)funcName;
/// appKey校验结果
/// \param result 校验结果 0 临时 1 成功 2 失败
///
- (void)bleAppKeyStateWithResult:(NSInteger)result;
/// 蓝牙状态回调
/// \param powered 是否可用？
///
- (void)bleStateWithPowered:(BOOL)powered;
@optional
/// 蓝牙连接阶段回调
/// \param sn 序列号（Serial Number），当前连接设备的唯一标识
///
/// \param stage 当前连接阶段，对应 <code>ConnectStage</code> 枚举的取值
///
/// \param detail 关于当前连接阶段的可选补充说明信息
///
- (void)bleConnectStageWithSn:(NSString * _Nullable)sn stage:(NSString * _Nonnull)stage detail:(NSString * _Nullable)detail;
@required
/// 蓝牙连接状态
/// <ul>
///   <li>
///     Parameters state: 0 断开连接或者未连接；1 连接成功；2 连接失败
///   </li>
/// </ul>
- (void)bleConnectStateWithState:(NSInteger)state;
/// 扫描蓝牙设备回调
/// \param bleDevices 蓝牙设备列表
///
- (void)bleScanResultWithBleDevices:(NSArray<BleDevice *> * _Nonnull)bleDevices;
/// 扫描超时结束
/// @see startScan
- (void)bleScanOverTime;
/// 等待用户确认
/// \param timeout 超时时长，单位秒
///
- (void)bleHandshakeWaitWithTimeout:(NSInteger)timeout;
/// 连接的回调
/// \param status 状态，0：成功，>0:拒绝 1：Token不匹配 2: 带屏的项目，正在录音，用户暂时无法确认 3：带屏的项目，用户手动拒绝  255：录音笔不在连接模式，非连接模式下拒绝握手请求（黑黎三段式开关特有）  <0 校验失败 -1: 没有SSN -2：网络异常 -3 : 服务器数据异常或校验不正确
///
/// \param protVersion 协议版本号
///
/// \param timezone 笔端当前时区
///
- (void)bleBindWithSn:(NSString * _Nullable)sn status:(NSInteger)status protVersion:(NSInteger)protVersion timezone:(NSInteger)timezone;
/// 设备名称
/// \param name 设备名称
///
- (void)bleDeviceNameWithName:(NSString * _Nullable)name;
/// 心跳消息
/// \param status 0 ping，1 pong，
///
- (void)bleHeartbeatWithStatus:(NSInteger)status;
/// 电池电量改变
/// \param power 现在的电量
///
/// \param oldPower 之前的电量（用于判断从20%->19%以及10%->9%低电提醒）
///
- (void)blePowerChangeWithPower:(NSInteger)power oldPower:(NSInteger)oldPower;
/// 电池电量状态
/// \param isCharging 是否插入充电器 0 未插入 1 插入 (BleDevice中有一个isCharging，会在该回调之后设置，可以比较前值，判断充电状态的改变)
///
/// \param level 电量 0-100
///
- (void)bleChargingStateWithIsCharging:(BOOL)isCharging level:(NSInteger)level;
/// 返回状态
/// \param state 根据项目自定义 (4099(0x00001003) 表示录音笔正在录音， 1好像是录音中)
///
/// \param privacy 隐私设置状态
///
/// \param keySatte 拨动开光状态(协议版本4新增）
///
/// \param uDisk U盘是否启用
/// 另外两个参数直接放在BleAgent中
///
/// \param scene 当前录音场景（没在录音是0）
///
/// \param findMyToken findmy token 是否存在（NotePin 设备）
///
/// \param hasSndpKey 声加 license token 是否存在
///
/// \param deviceAccessToken 设备闲时同步的 AccessToken 是否存在
///
/// \param sessionId 当前会话id（没在录音时为0）
///
- (void)blePenStateWithState:(NSInteger)state privacy:(NSInteger)privacy keyState:(NSInteger)keyState uDisk:(NSInteger)uDisk findMyToken:(NSInteger)findMyToken hasSndpKey:(NSInteger)hasSndpKey deviceAccessToken:(NSInteger)deviceAccessToken versionType:(NSString * _Nonnull)versionType versionCode:(NSInteger)versionCode;
/// 同步时间的回调
/// \param stamp GMT时间戳
///
/// \param timezone 时区
///
/// \param zoneMin 时区分钟部分
/// 数据会保存在device实体类中，用于通过sessionId转换为时间戳
///
- (void)blePenTimeWithStamp:(NSInteger)stamp timezone:(NSInteger)timezone zoneMin:(NSInteger)zoneMin;
/// 录音笔空间
/// \param total 空间总大小（字节）
///
/// \param free 剩余空间大小（字节）
///
/// \param duration 录音笔估算的剩余录音时长（毫秒）
///
- (void)bleStorageWithTotal:(NSInteger)total free:(NSInteger)free duration:(NSInteger)duration;
/// 重置密码
/// \param password 重置后的初始密码
///
- (void)blePasswordResetWithPassword:(NSInteger)password;
/// 读取获取设置背光时长的回调
/// \param duration 时长的枚举 0: 10秒 1：20秒 2： 30秒 4： 始终亮屏
///
- (void)bleBacklightDuration:(NSInteger)duration;
/// 读取或设置背光对比度（亮度）的回调
/// \param bright 亮度的等级 1-6
///
- (void)bleBacklightBright:(NSInteger)bright;
/// 语言
/// \param type 0 简体中文 1 繁体中文 2 英语
///
- (void)bleLanguage:(NSInteger)type;
/// 录音场景
/// \param scene 0 Unknown; 1 Normal; 2 Interview; 3 Classroom(Speech); 4 Music; 5 Meeting; 6 Memo
///
- (void)bleRecScene:(NSInteger)scene;
/// 录音模式
/// \param mode 1 Normal (正常，非降噪); 2 NC (降噪)
///
- (void)bleRecMode:(NSInteger)mode;
/// vad 灵敏度
/// \param value 1：Quality; 2：Normal； 3：Aggressive
///
- (void)bleVadSensitivity:(NSInteger)value;
/// 电池模式
/// \param value 0：默认，1：长续航
///
- (void)bleBatteryMode:(NSInteger)value;
/// vpu 灵敏度
/// \param value 1：Low; 2：Medium； 3：High
///
- (void)bleVpuGain:(NSInteger)value;
/// vpu 灵敏度
/// \param value 1- 30
///
- (void)bleMicGain:(NSInteger)value;
/// SWITCH开关功能
/// \param id 0：通话场景切换    1：录音功能    2：关机功能
///
- (void)bleSwitchHandler:(NSInteger)id;
/// 定时关机功能
/// \param value 0：关闭    1：立即关机    2：15分钟    3：30分钟    4：1个小时    5：5个小时
///
- (void)bleAutoPowerOff:(NSInteger)value;
/// 设备存储 raw wav 文件
/// \param value 0：关闭    1：开启
///
- (void)bleRawWaveEnabled:(NSInteger)value;
/// 充电器拔出后开始录音
/// \param value 0：关闭    1：开启
///
- (void)bleRecordingAfterDisConnetEnabled:(NSInteger)value;
/// 闲时同步
/// \param value 0：关闭    1：开启
///
- (void)bleSyncWhenIdleEnabled:(NSInteger)value;
/// iBeacon 唤醒 APP 开关
/// \param value 0：关闭    1：开启
///
- (void)bleIBeaconWakeupEnabled:(NSInteger)value;
/// findmy 状态
/// \param value 
/// 0：未绑定状态 - 关闭广播
/// 1：未绑定状态 - 开启广播
/// 2：绑定状态 - 可被查找
/// 3：绑定状态 - 不可被查找
///
- (void)bleFindMyState:(NSInteger)value;
/// \param value 
/// 0：关闭
/// 1：开启
///
- (void)bleVPUCLKState:(NSInteger)value;
/// \param value 
/// 0：关闭
/// 1：开启
///
- (void)bleStopRecordingAfterCharging:(NSInteger)value;
/// 自动清除录音状态
/// 注意：录音笔仅保存状态，是否在同步完录音后删除录音，app自行决定
/// \param open  是否开启 
///
- (void)bleAutoClear:(BOOL)open;
/// vad开关状态
/// \param open 是否开启 
///
- (void)bleVad:(BOOL)open;
/// 解绑
/// \param status 0 成功 ；1 正在工作 2 正在升级
///
- (void)bleDepair:(NSInteger)status;
/// WiFi开启通知
/// \param status 0 正常，>1 禁止开启 1 录音状态，2 U盘状态
///
/// \param wifiName 录音笔热点名称
///
/// \param wholeName 判断是否要追加4位sn后的名称
///
/// \param wifiPass 录音笔热点密码
///
- (void)bleWiFiOpen:(NSInteger)status :(NSString * _Nonnull)wifiName :(NSString * _Nonnull)wholeName :(NSString * _Nonnull)wifiPass;
/// WiFi关闭通知
/// \param status 0 成功 1 wifi没有开启
///
- (void)bleWiFiClose:(NSInteger)status;
/// WiFi配网结果
/// \param status 0 成功； 1 参数长度不对
///
- (void)bleSetWiFiSsidWithStatus:(NSInteger)status;
/// WiFi配网查询结果
/// \param status 0 连接中
///
/// \param ssid wifi
///
- (void)bleGetWiFiSsidWithStatus:(NSInteger)status ssid:(NSString * _Nullable)ssid;
/// 录音声音异常提醒
/// \param status 0 正常 1 敲击/声音截幅 2 声音过大 3 声音太小 4 噪音太大
///
- (void)bleVoiceAbnormalWithStatus:(NSInteger)status;
/// 设置或者获取服务器配置
/// \param type 1 服务器url 2 服务器token 3 设备端token
///
/// \param conent url / serToken / devToken
///
- (void)bleWebsocketProfile:(NSInteger)type :(NSString * _Nullable)conent;
/// 服务器测试
/// \param status 0 成功；1 未扫描到AP  2 AP密码错误  3  websocket连接失败
///
- (void)bleWebsocketTest:(NSInteger)status;
/// 开始录音的回调
/// \param sessionId 录音文件唯一id，0时区时间戳，换成手机当前时间戳需要减掉时区
///
/// \param start 已录音时长（文件偏移量，字节）（如果之前不在录音，返回0；如果之前在录音，返回已录音的时长）
///
/// \param status 0：成功，>0：失败 1：空间已满；2：U盘模式；3：硬件异常；4：当前正忙； 255：模式不对(录音笔不在录音模式，黑黎三段式开关特有)
///
/// \param scene 录音模式（依项目、版本号而定）
///
/// \param startTime 开始时间（依项目、版本号而定）
///
- (void)bleRecordStartWithSessionId:(NSInteger)sessionId start:(NSInteger)start status:(NSInteger)status scene:(NSInteger)scene startTime:(NSInteger)startTime;
/// 结束录音的回调
/// \param sessionId 录音文件唯一id，0时区时间戳，换成手机当前时间戳需要减掉时区
///
/// \param reason 原因（其余未定义）
/// 1.MMI_REC_STOP_FROM_DEV    /// 设备端停止录音
/// 2.MMI_REC_STOP_FROM_APP    /// APP端停止录音
/// 3.MMI_REC_STOP_BY_SPLIT        /// 自动时间切片停止录音
/// 4.MMI_REC_STOP_BY_SWITCH   ///  switch开关切换停止录音 ）
///
/// \param fileExist 文件是否保存
///
/// \param fileSize 文件大小（如果有的话，字节）
///
- (void)bleRecordStopWithSessionId:(NSInteger)sessionId reason:(NSInteger)reason fileExist:(BOOL)fileExist fileSize:(NSInteger)fileSize;
/// 录音暂停的回调
/// \param sessionId 录音文件唯一id，0时区时间戳，换成手机当前时间戳需要减掉时区
///
/// \param reason 原因（目前未定义）
///
/// \param fileExist 文件是否保存
///
/// \param fileSize 文件大小（如果有的话，字节）
///
- (void)bleRecordPauseWithSessionId:(NSInteger)sessionId reason:(NSInteger)reason fileExist:(BOOL)fileExist fileSize:(NSInteger)fileSize;
/// 录音恢复（固件版本7开始）
/// \param sessionId 录音文件唯一id，0时区时间戳，换成手机当前时间戳需要减掉时区
///
/// \param start 已录音时长（文件偏移量，字节）（如果之前不在录音，返回0；如果之前在录音，返回已录音的时长）
///
/// \param status 0：成功，>0：失败 1：空间已满；2：U盘模式；3：硬件异常
///
/// \param scene 录音模式（依项目、版本号而定）
///
/// \param startTime 开始时间（依项目、版本号而定）
///
- (void)bleRecordResumeWithSessionId:(NSInteger)sessionId start:(NSInteger)start status:(NSInteger)status scene:(NSInteger)scene startTime:(NSInteger)startTime;
/// 获取录音灯效
- (void)bleLedStateOnOff:(NSInteger)onOff;
/// 设置录音灯效
- (void)bleSetLedStateOnOff:(NSInteger)onOff;
/// 获取文件列表的回调
/// \param bleFiles 文件列表
///
- (void)bleFileListWithBleFiles:(NSArray<BleFile *> * _Nonnull)bleFiles;
/// 同步（下载）文件开始的回调
/// \param sessionId 文件唯一id
///
/// \param status 状态，0：成功；>0：失败 1：文件系统当前不可用 2：文件不存在 3： 被打断
///
- (void)bleSyncFileHeadWithSessionId:(NSInteger)sessionId status:(NSInteger)status;
/// 同步（下载）文件结束
/// \param sessionId 文件唯一id
///
/// \param crc 文件校验码，校验文件完整性(录音笔改为egg保存文件后不要用)
///
- (void)bleSyncFileTailWithSessionId:(NSInteger)sessionId crc:(NSInteger)crc;
/// 返回录音打点数据
/// \param sessionId 会话id
///
/// \param status 状态 0 正常 1 当前文件系统不可用
///
/// \param markList 打点数据
///
- (void)bleMarkingWithSessionId:(NSInteger)sessionId status:(NSInteger)status markList:(NSArray<NSNumber *> * _Nonnull)markList;
/// 返回录音打点数据(3.0新协议)
/// \param uid 请求uid
///
/// \param totals 总条数
///
/// \param index 当前包索引
///
/// \param tags 打点数据列表，包含时间戳、类型、状态和保留字段
///
- (void)bleGetRecordMarkingTagsWithUid:(NSInteger)uid totals:(NSInteger)totals index:(NSInteger)index tags:(NSArray<BleRecordMarkingTag *> * _Nonnull)tags;
/// 角度上报
/// \param pitchAngle 俯仰角 -180~180
///
/// \param rollbackAngle 回滚角 -180~180
///
/// \param yawAngle 偏航角 -180~180
///
- (void)bleAnglesWithPitchAngle:(float)pitchAngle rollbackAngle:(float)rollbackAngle yawAngle:(float)yawAngle;
/// 数据接收完了
- (void)bleDataComplete;
/// 语音数据返回
/// \param sessionId 文件的id，协议7支持
///
/// \param start 数据在未解码文件中的偏移量（字节）
///
/// \param data 数据（可能是ogg数据也可能是opus纯音频，由固件决定）
///
- (void)bleDataWithSessionId:(NSInteger)sessionId start:(NSInteger)start data:(NSData * _Nonnull)data;
/// log文件数据下载
/// \param start 当前数据包偏移量
///
/// \param data 数据包
///
- (void)deviceLogDataWithStart:(NSInteger)start data:(NSData * _Nonnull)data logType:(NSInteger)logType;
/// 返回解码后的pcm数据
/// \param sessionId 文件的id，协议7支持
///
/// \param millsec 当前语言毫秒值
///
/// \param pcmData 解码后的数据，如果开始录音的时候没有要求解码，不会回调；如果录音是双声道，这里会处理为单声道；音乐模式是双声道48k采样率，会处理成单声道48k，不可用于识别
///
/// \param isMusic 是不是音乐模式？音乐模式返回的pcm不是正常的pcm，是6个short取一个，用于生成声波，不能用于识别
///
- (void)blePcmDataWithSessionId:(NSInteger)sessionId millsec:(NSInteger)millsec pcmData:(NSData * _Nonnull)pcmData isMusic:(BOOL)isMusic;
/// 语音数据解码失败
/// \param start 数据在未解码文件中的偏移量
///
- (void)bleDecodeFailWithStart:(NSInteger)start;
/// 同步文件终止
- (void)bleSyncFileStop;
/// 删除文件
/// \param sessionId 协议版本7支持
///
/// \param status 状态，0：删除成功；1：正在录音不允许删除  2: 已收藏不允许删除; 3: 正在播放不允许删除
///
- (void)bleDeleteFileWithSessionId:(NSInteger)sessionId status:(NSInteger)status;
/// ota通知
/// \param uid 标识
///
/// \param status 状态 0 正常，1. 升级失败 2. 版本信息不匹配  3.FLASH写失败 4.文件太大 5.尝试次数过多  6. U盘模式；7.正在录音； 8. U盘剩余空间不足；  9. 正在工作中; 10. G101眼镜仅在充电模式允许升级；11. G101眼镜电池电量不足；12. G101眼镜收到升级协议并准备调整到OTA_MODE; 255：模式不对(录音笔不在录音模式，黑黎三段式开关特有)
///
/// \param errmsg 协议版本4，如果升级成功，这里返回升级后的版本；如果失败，依然返回错误信息。
///
- (void)bleFotaResultWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
/// ota包请求，录音笔请求发送升级包数据
/// \param uid 标识
///
/// \param start 开始位置（字节）
///
/// \param end 结束位置（字节）
///
- (void)bleFotaPackReqWithUid:(NSInteger)uid start:(NSInteger)start end:(NSInteger)end;
/// ota包接收完成
/// \param uid 标识
///
/// \param status 状态 0 正常，1. 升级失败 2. 版本信息不匹配  3.FLASH写失败 4.文件太大 5尝试次数过多  6. U盘模式；7.正在录音； 8. U盘剩余空间不足
///
/// \param errmsg 协议版本4，如果升级成功，这里返回升级后的版本；如果失败，依然返回错误信息。
///
- (void)bleFotaPackFinWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
/// ota数据发送失败
- (void)bleOtaDataSendFail;
/// 蓝牙传输速率的回调
/// \param lossRate 丢包率
///
/// \param rate 平均速率，字节/S
///
/// \param instantRate 实时速率
///
- (void)bleRateWithLossRate:(double)lossRate rate:(NSInteger)rate instantRate:(NSInteger)instantRate;
/// 隐私设置
/// 开启时，禁止笔端播放，禁止U盘功能，禁止笔端解除绑定
- (void)blePrivacyWithPrivacy:(NSInteger)privacy;
/// 清空笔端所有文件
/// 0：删除成功；1：正在录音文件不允许删除；2：已收藏不允许删除； 3：正在播放文件不允许删除；4：U盘模式
- (void)bleClearAllFileWithStatus:(NSInteger)status;
/// 设备状态读取
/// status[4]：4字节状态数组，包含设备状态位信息
/// 原始数据格式：32位状态值，每个位代表一个状态
/// 已知状态位定义：
/// bit0: BLE文件传输, bit1: WiFi快传, bit2: WiFi测试中, bit3: 有线传输中
/// bit4: U盘模式中, bit5: wifi上云中, bit6: pan上云中, bit7: BLEota下载中
/// bit8: WiFiota下载中, bit9: OTA升级中
/// 注意：返回原始数据，应用层可自行解析，支持设备后续新增状态位
- (void)bleDeviceStatusWithStatus:(NSArray<NSNumber *> * _Nonnull)status;
/// OTA下载进度（cmd 151）
- (void)bleSyncOtaFileInfoWithUid:(uint32_t)uid start:(uint32_t)start end:(uint32_t)end toVersion:(uint32_t)toVersion toVersionType:(uint8_t)toVersionType isSilent:(NSInteger)isSilent packetCheckOk:(NSInteger)packetCheckOk;
/// 设备支持的feature功能
- (void)bleNewFeatureWithData:(NSData * _Nonnull)data;
/// 定时录音
/// \param start 开始时间（UTC）； 0 表示关闭定时录音
///
/// \param duration 录音时长（单位s）
///
/// \param repeatMode 0 once仅一次有效; 1 daily每天； 2 weekly每周
///
- (void)bleAlarmRecWithStart:(NSInteger)start duration:(NSInteger)duration repeatMode:(NSInteger)repeatMode;
/// 唤醒、休眠设置
/// 0：休眠；1：唤醒
- (void)bleSetActiveWithStatus:(NSInteger)status;
/// binaryFile基础信息同步 - FindMy Token
/// \param type 文件扩展类型（长度 1 byte）
///
/// \param packageOffset 文件读取偏移值(4byte)
///
/// \param packageSize 请求获取一段数据的大小(2byte)
///
/// \param endStatus 文件结束，0还需要数据；(1byte)
///
- (void)onBinaryFileReqWithType:(NSInteger)type packageOffset:(NSInteger)packageOffset packageSize:(NSInteger)packageSize endStatus:(NSInteger)endStatus;
/// 发送二进制数据 - FindMy Token 设置
/// \param result 成功 0 /（失败1或者其他原因）(1byte)
///
- (void)onBinaryFileEndWithResult:(NSInteger)result;
/// 闲时同步 WiFi 配置接收
/// \param index WiFi 编号 (4 bytes)
///
/// \param ssid WiFi SSID
///
/// \param password WiFi 密码
///
- (void)onSyncIdleWifiConfigReceivedWithIndex:(uint32_t)index ssid:(NSString * _Nonnull)ssid password:(NSString * _Nonnull)password;
/// 设置闲时同步 WiFi 配置结果
/// \param result 结果代码 (0: 成功, 1: 已存在, 2: 未找到删除设备, 3: 未找到变更, 4: 操作码异常, 5: 队列已满, 其他: 其他错误)
///
- (void)onSyncIdleWifiConfigSetWithResult:(NSInteger)result;
/// 闲时同步 WiFi 列表接收
/// \param list WiFi 索引列表
///
- (void)onSyncIdleWifiListReceivedWithList:(NSArray<NSNumber *> * _Nonnull)list;
/// 闲时同步 WiFi 删除结果
/// \param result 结果代码 (0: 成功, -1: 失败)
///
- (void)onSyncIdleWifiDeleteResultWithResult:(NSInteger)result;
/// 闲时同步 WiFi 测试开始
/// \param index WiFi 编号
///
- (void)onSyncIdleWifiTestStartedWithIndex:(uint32_t)index;
/// 闲时同步即将开始开始
/// \param second 即将开始的秒数
///
- (void)onSyncIdleWillStartWithSeconds:(NSInteger)seconds;
/// 闲时同步 WiFi 测试结果
/// \param index WiFi 编号
///
/// \param result 测试结果：0, 测试成功 1,未找到wifi 2,Wifi密码不正确 3,Wifi连接失败 4,数据传输失败
///
/// \param rawCode 原始错误码
///
- (void)onSyncIdleWifiTestResultWithIndex:(uint32_t)index result:(NSInteger)result rawCode:(NSInteger)rawCode;
/// 重置 findmy 状态结果
/// \param result 测试结果：0, 测试成功 1,未找到wifi 2,Wifi密码不正确 3,Wifi连接失败 4,数据传输失败
///
- (void)onResetFindmyResultWithResult:(NSInteger)result;
/// 通用参数设置结果
/// \param success 是否成功
///
/// \param dataType 字符串类型（1: WiFi上云域名/ip, 2: findmy PPID）
///
/// \param value 返回的字符串内容（失败时可能为空）
///
- (void)onCommonParamsSetResultWithSuccess:(BOOL)success dataType:(NSInteger)dataType value:(NSString * _Nullable)value;
/// 通用参数读取结果
/// \param success 是否成功
///
/// \param dataType 字符串类型（1: WiFi上云域名/ip, 2: findmy PPID）
///
/// \param value 返回的字符串内容（失败时可能为空）
///
- (void)onCommonParamsGetResultWithSuccess:(BOOL)success dataType:(NSInteger)dataType value:(NSString * _Nullable)value;
- (void)onSetSoundPlusTokenResultWithLicenseKey:(NSString * _Nonnull)licenseKey;
- (void)onGetSDFlashCIDResultWithCid:(NSString * _Nonnull)cid;
- (void)onGetDeviceLogListWithData:(NSData * _Nonnull)data;
- (void)onSyncDeviceLogStartWithData:(NSData * _Nonnull)data;
- (void)onSyncDeviceLogStop;
- (void)onSyncDeviceLogEndWithData:(NSData * _Nonnull)data;
- (void)onDeviceLogDeletedWithData:(NSData * _Nonnull)data;
@end


SWIFT_CLASS("_TtC11PlaudBleSDK9BleDevice")
@interface BleDevice : NSObject
/// 录音笔的名称
@property (nonatomic, copy) NSString * _Nonnull name;
/// uuid
@property (nonatomic, copy) NSString * _Nonnull uuid;
/// 蓝牙信号强度
@property (nonatomic) float rssi;
/// 厂商类型，MTK或Nordic
@property (nonatomic, copy) NSString * _Nonnull manufacturer;
/// 项目代码
@property (nonatomic) NSInteger projectCode;
/// 版本类型，T或V
@property (nonatomic, copy) NSString * _Nonnull versionTypeStr;
/// 版本号
@property (nonatomic) NSInteger versionCode;
/// SN，设备唯一编号
@property (nonatomic, copy) NSString * _Nonnull serialNumber;
/// 绑定状态 0 未绑定，1 已绑定
@property (nonatomic) NSInteger bindCode;
/// 设备电池电量
@property (nonatomic) NSInteger power;
/// 设备是否正在充电
@property (nonatomic) BOOL isCharging;
/// 空间总大小
@property (nonatomic) NSInteger total;
/// 设备剩余空间
@property (nonatomic) NSInteger free;
/// 录音笔估算的剩余录音时长
@property (nonatomic) NSInteger duration;
/// 设备当前时区
@property (nonatomic) NSInteger timezone;
/// 时区的分钟部分
@property (nonatomic) NSInteger zoneMin;
/// 声道数
@property (nonatomic) NSInteger channels;
/// 是否支持WiFi
@property (nonatomic) BOOL supportWiFi;
/// 是否需要App端做降噪、增益
@property (nonatomic) BOOL nsAgc;
/// 同步的是ogg完整数据还是纯音频opus？
@property (nonatomic) BOOL isOgg;
/// 是否在同步完语音数据后删除录音笔中的文件
@property (nonatomic) NSInteger autoClear;
/// 是否隐蔽录音
@property (nonatomic) NSInteger hideLed;
/// 根据项目自定义 (4099（0x00001003） 表示录音笔正在录音)
@property (nonatomic) NSInteger state;
/// 是否开启隐私设置 1 开启；0 关闭
@property (nonatomic) NSInteger privacy;
/// 拨动开光状态， 0 无状态 1 录音状态 2 闲置状态
/// Plaud：3 Switch on 4 Switch off
@property (nonatomic) NSInteger keyState;
/// U盘是否启用， 0 未启用 1 已启用
@property (nonatomic) NSInteger uDisk;
/// finmy token 是否存在，0 不存在，1 存在
@property (nonatomic) NSInteger findmyToken;
/// 是否有升级包（通过http访问服务器获取，放在这里方便使用）
@property (nonatomic) BOOL hasFota;
/// 判断是否要添加四位SN后的名称
@property (nonatomic, readonly, copy) NSString * _Nonnull wholeName;
/// WiFi热点的名字
@property (nonatomic, readonly, copy) NSString * _Nonnull wifiName;
- (nonnull instancetype)initWithSn:(NSString * _Nonnull)sn OBJC_DESIGNATED_INITIALIZER;
/// 版本号对外显示
///
/// returns:
/// 版本号显示字符串
- (NSString * _Nonnull)wholeVersion SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
/// 8：30 –> 8<em>3600+30</em>60
/// -2: 45 –> -2<em>3600-45</em>60
- (NSInteger)zoneSecond SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class CBService;
@class CBCharacteristic;

@interface BleDevice (SWIFT_EXTENSION(PlaudBleSDK)) <CBPeripheralDelegate>
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverServices:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didDiscoverCharacteristicsForService:(CBService * _Nonnull)service error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateNotificationStateForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didUpdateValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
- (void)peripheral:(CBPeripheral * _Nonnull)peripheral didWriteValueForCharacteristic:(CBCharacteristic * _Nonnull)characteristic error:(NSError * _Nullable)error;
@end


/// 录音文件实例类
SWIFT_CLASS("_TtC11PlaudBleSDK7BleFile")
@interface BleFile : NSObject
/// 录音设备的唯一标识（该录音属于哪个录音笔）
@property (nonatomic, copy) NSString * _Nonnull sn;
/// 录音笔中录音文件id，唯一
@property (nonatomic) NSInteger sessionId;
/// 文件大小
@property (nonatomic) NSInteger size;
/// 文件偏移量，即当前文件下载位置
@property (nonatomic) NSInteger offset;
/// 当前时区
/// 笔端文件名是当地时间，如果要转成UTC时间，就需要把时区减掉
@property (nonatomic) NSInteger timezone;
/// 时区的分钟部分（部分国家地区会有带分钟的时区）
@property (nonatomic) NSInteger zoneMin;
/// 场景（协议7支持）
@property (nonatomic) NSInteger scenes;
/// 是否笔端收藏
@property (nonatomic) NSInteger penCollect;
/// 声道数
@property (nonatomic) NSInteger channels;
/// 是否需要App端降噪、增益
@property (nonatomic) BOOL nsAgc;
/// 传输的是ogg文件还是opus？
@property (nonatomic) BOOL isOgg;
/// 是不是音乐模式下的录音？
@property (nonatomic, readonly) BOOL isMusic;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 初始化
/// \param sessionId 文件唯一id
///
/// \param fileSize 文件大小，文件时长通过文件大小来计算
///
- (nonnull instancetype)init:(NSInteger)sessionId :(NSInteger)size OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)sn :(NSInteger)sessionId :(NSInteger)size OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)sn :(NSInteger)sessionId :(NSInteger)size :(NSInteger)channels :(BOOL)nsAgc OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSString * _Nonnull)sn :(NSInteger)sessionId :(NSInteger)size :(NSInteger)scenes :(NSInteger)penCollect :(NSInteger)channels :(BOOL)nsAgc OBJC_DESIGNATED_INITIALIZER;
/// 获取录音文件时长
///
/// returns:
/// 时长，单位毫秒
- (NSInteger)duration SWIFT_WARN_UNUSED_RESULT;
/// ogg文件大小转时长(不会十分严谨，误差在100ms内）
///
/// returns:
/// 时长，单位毫秒
/// @depared 返回的是duration()，以后的版本会移除该方法
- (NSInteger)oggDuration SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
/// 计算录音文件时长
/// \param fileSize 文件大小
///
/// \param channel 声道数
///
/// \param isOgg 是不是ogg文件？
///
/// \param scenes 场景， 如果是会议模式(4)，那么传输的是Wave，需要特殊处理
///
///
/// returns:
/// 时长，毫秒
+ (NSInteger)calculateDuration:(NSInteger)fileSize :(NSInteger)channel :(BOOL)isOgg :(NSInteger)scenes SWIFT_WARN_UNUSED_RESULT;
@end


@interface BleFile (SWIFT_EXTENSION(PlaudBleSDK)) <NSCopying>
/// 深拷贝
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
/// 时区转秒
- (NSInteger)zoneSecond SWIFT_WARN_UNUSED_RESULT;
/// 通过sessionId（utc 0时区时间）和时区获取的本地时间戳
- (NSInteger)utsStamp SWIFT_WARN_UNUSED_RESULT;
@end


/// 录音打点数据(3.0新协议)
SWIFT_CLASS("_TtC11PlaudBleSDK19BleRecordMarkingTag")
@interface BleRecordMarkingTag : NSObject
@property (nonatomic, readonly) uint32_t timestamp;
@property (nonatomic, readonly) uint8_t type;
@property (nonatomic, readonly) uint8_t status;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull reserved;
- (nonnull instancetype)initWithTimestamp:(uint32_t)timestamp type:(uint8_t)type status:(uint8_t)status reserved:(NSArray<NSNumber *> * _Nonnull)reserved OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




/// 眼镜记录报表数据
SWIFT_CLASS("_TtC11PlaudBleSDK9GlassData")
@interface GlassData : NSObject
@property (nonatomic) NSInteger year;
@property (nonatomic) NSInteger month;
@property (nonatomic) NSInteger day;
@property (nonatomic) NSInteger time;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(uint16_t)year :(uint8_t)month :(uint8_t)day :(uint32_t)time OBJC_DESIGNATED_INITIALIZER;
@end


/// 眼镜专有数据的代理
SWIFT_PROTOCOL("_TtP11PlaudBleSDK13GlassProtocol_")
@protocol GlassProtocol
/// 眼镜报表数据
/// \param delFlag 删除次数统计
///
/// \param dataArr 报表数据
///
- (void)glassData:(NSInteger)delFlag :(NSArray<GlassData *> * _Nonnull)dataArr;
/// 清除报表数据
/// \param status 0 成功；1 设备正在使用，删除失败
///
- (void)glassDataClear:(NSInteger)status;
@end


SWIFT_CLASS_NAMED("JXAvcDecoder")
@interface JXAvcDecoder : NSObject
/// 单声道单个包大小
@property (nonatomic, readonly) NSInteger packSize;
/// 双声道单个包大小
@property (nonatomic, readonly) NSInteger twoChannelPackSize;
/// 4声道单个包大小
@property (nonatomic, readonly) NSInteger fourChannelPackSize;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 创建解码器
/// \param channels 声道数，默认1
///
- (void)createDecoderIfNeed:(NSInteger)channels;
/// 解码单个数据包
/// 如果解码器异常或者被回收，会重新创建并初始化
/// \param data 待解码数据，长度是 80 * channels
///
///
/// returns:
/// 解码后的数据
- (NSData * _Nullable)decode:(NSData * _Nonnull)data :(NSInteger)channels SWIFT_WARN_UNUSED_RESULT;
/// 释放解码器
- (void)releaseDecoder;
@end


/// crc工具类
/// 同步（下载）录音笔的文件，自己控制好偏移量拼接好，文件就不会错，crc是对不上的（笔端文件和发给app的不一样）
/// 给录音笔下发差分升级包需要给录音笔传一个crc校验文件的完整性
SWIFT_CLASS("_TtC11PlaudBleSDK11JXCrcHelper")
@interface JXCrcHelper : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXCrcHelper * _Nonnull shared;)
+ (JXCrcHelper * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 获取文件的CRC校验码
/// \param path 文件路径
///
///
/// returns:
/// 校验码，如果文件不存在，返回-1
- (NSInteger)getCrcWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
/// 校验文件CRC
/// \param crc 笔端返回的crc值
///
/// \param path 文件路径
///
///
/// returns:
/// 文件是否完整
- (BOOL)checkCrcWithCrc:(NSInteger)crc ofFile:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
@end


/// 音频解码、格式转换工具类
SWIFT_CLASS("_TtC11PlaudBleSDK13JXFileDecoder")
@interface JXFileDecoder : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXFileDecoder * _Nonnull shared;)
+ (JXFileDecoder * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// pcm转wav
/// \param pcmPath pcm文件路径
///
/// \param wavPath wav文件路径
///
/// \param channels 声道数，默认1
///
/// \param simpleRate 采样率，默认16000
///
/// \param completionHandler 回调
///
- (void)pcmToWavWithPcmPath:(NSString * _Nonnull)pcmPath wavPath:(NSString * _Nonnull)wavPath channels:(uint32_t)channels simpleRate:(uint32_t)simpleRate completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
/// 音乐模式下录制的音频，且一开始进行了实时录音的同步，那么wav头信息需要重新设置以下才能用普通播放器播放
/// \param wavPath wav文件路径
///
/// \param channels 声道数，音乐模式是双声道
///
/// \param sampleRate 采样率，音乐模式是48000（48k）
///
- (void)resetWavHead:(NSString * _Nonnull)wavPath :(uint32_t)channels :(uint32_t)sampleRate;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasAvcToWavTask SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)convertAvcToWavCancel;
/// avc未解码数据转wav，如果有多个，会按照队列依次执行
/// 实现改为了c语言
/// \param avcPath 原始数据文件路径
///
/// \param wavPath wav文件路径
///
/// \param channels 声道数，默认1
///
/// \param ns_agc 是否做降噪、增益
///
/// \param clearUnfinished 如果任务队列中海油之前未完成的任务，会取消掉
///
/// \param completionHandler 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)avcToWavWithAvcPath:(NSString * _Nonnull)avcPath wavPath:(NSString * _Nonnull)wavPath channels:(int32_t)channels ns_agc:(BOOL)ns_agc clearUnfinished:(BOOL)clearUnfinished completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasPcmToMp3Task SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)convertPcmToMp3Cancel;
/// pcm录音文件转mp3，如果有多个，会按照队列依次执行
/// 不知道为什么生成的mp3不能用AVAudioPlayer播放，用AVPlayer播放是可以的
/// \param pcmPath pcm文件路径
///
/// \param mp3Path 要生成的MP3文件路径
///
/// \param clearUnfinished 如果任务队列中海油之前未完成的任务，会取消掉
///
/// \param quality 2 near-best quality, not too slow; 5 good quality, fast; 7 ok quality, really fast
///
/// \param channels 声道数，默认1
///
/// \param completionHandler 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)pcmToMp3WithPcmPath:(NSString * _Nonnull)pcmPath mp3Path:(NSString * _Nonnull)mp3Path clearUnfinished:(BOOL)clearUnfinished quality:(int32_t)quality channels:(int32_t)channels completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasAvcToMp3Task SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)convertAvcToMp3Cancel;
/// avc原始录音文件转mp3，如果有多个，会按照队列依次执行
/// 不知道为什么生成的mp3不能用AVAudioPlayer播放，用AVPlayer播放是可以的
/// \param avcPath avc原始录音文件路径
///
/// \param mp3Path 要生成的MP3文件路径
///
/// \param clearUnfinished 如果任务队列中还有之前未完成的任务，会取消掉
///
/// \param quality 2 near-best quality, not too slow; 5 good quality, fast; 7 ok quality, really fast
///
/// \param channels 声道数，默认1
///
/// \param ns_agc 是否要做降噪、增益
///
/// \param completionHandler 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)avcToMp3WithAvcPath:(NSString * _Nonnull)avcPath mp3Path:(NSString * _Nonnull)mp3Path clearUnfinished:(BOOL)clearUnfinished quality:(int32_t)quality channels:(int32_t)channels ns_agc:(BOOL)ns_agc completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasOggToMp3Task SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)convertOggToMp3Cancel;
/// ogg压缩mp3
/// \param oggPath ogg文件路径
///
/// \param mp3Path mp3文件路径
///
/// \param channels ogg声道数
///
/// \param quality mp3音质 2 near-best quality, not too slow；5 good quality, fast；7 ok quality, really fast 默认7
///
/// \param callback 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)oggToMp3:(NSString * _Nonnull)oggPath :(NSString * _Nonnull)mp3Path :(int32_t)channels :(int32_t)quality :(void (^ _Nonnull)(BOOL, NSInteger))callback;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasOggMulToSingleTask SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)oggMulToSingleCancel;
/// 多声道ogg转单声道ogg，多声道可以是单、双、四声道；
/// 转后的ogg略小，可以谷歌浏览器播放
/// \param mulPath 多声道ogg地址
///
/// \param singlePath 目标单声道地址
///
/// \param channels 多声道ogg声道数
///
/// \param callback 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)oggMulToSingle:(NSString * _Nonnull)mulPath :(NSString * _Nonnull)singlePath :(int32_t)channels :(void (^ _Nonnull)(BOOL, NSInteger))callback;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
- (BOOL)hasAvcToNoiseReductionWav SWIFT_WARN_UNUSED_RESULT;
- (void)convertAvcToNoiseReductionWavCancel;
/// avc未解码数据转wav，如果有多个，会按照队列依次执行
/// 实现改为了c语言
/// \param avcPath 原始数据文件路径
///
/// \param wavPath wav文件路径
///
/// \param channels 声道数，默认1
///
/// \param ns_agc 是否做降噪、增益
///
/// \param clearUnfinished 如果任务队列中海油之前未完成的任务，会取消掉
///
/// \param completionHandler 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)avcToNoiseReductionWavWithAvcPath:(NSString * _Nonnull)avcPath wavPath:(NSString * _Nonnull)wavPath channels:(int32_t)channels sound_plus:(BOOL)sound_plus noiseReductionGain:(NSInteger)noiseReductionGain clearUnfinished:(BOOL)clearUnfinished completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasAvcToOggTask SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)convertAvcToOggCancel;
- (void)oggToOpus:(NSString * _Nonnull)oggPath :(NSString * _Nonnull)opusPath :(int32_t)channels :(void (^ _Nonnull)(BOOL))callback;
/// avc(opus)转ogg，网易云可以播放，思必驰、讯飞可以识别
/// \param avcPath avc(opus)文件路径
///
/// \param oggPath 目标ogg文件路径
///
/// \param clearUnfinished 如果任务队列中海油之前未完成的任务，会取消掉
///
/// \param iflyToolongCut 讯飞超长截取，默认打开（最长限制到4小时59分50秒）
///
/// \param channels 声道数，默认1
///
/// \param targetChannels 目标声道数（双声道默认转成单声道，也可以指定为双声道， 单声道不能转双声道）
///
/// \param ns_agc 是否要做降噪、增益
///
/// \param callback 回调函数，完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)avcToOgg:(NSString * _Nonnull)avcPath :(NSString * _Nonnull)oggPath clearUnfinished:(BOOL)clearUnfinished :(BOOL)iflyToolongCut :(int32_t)channels :(int32_t)targetChannels :(BOOL)ns_agc :(void (^ _Nonnull)(BOOL, NSInteger))callback;
@end


@interface JXFileDecoder (SWIFT_EXTENSION(PlaudBleSDK))
/// 是否有未完成任务
- (BOOL)hasAvcToPcmTask SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)convertAvcToPcmCancel;
/// avc文件转pcm
/// \param avcPath avc/opus文件路径
///
/// \param pcmPath pcm文件路径
///
/// \param clearUnfinished 如果任务队列中还有之前未完成的任务，会取消掉
///
/// \param channels 声道数，默认1
///
/// \param ns_agc 是否要做降噪、增益
///
/// \param completionHandler 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)avcToPcmWithAvcPath:(NSString * _Nonnull)avcPath pcmPath:(NSString * _Nonnull)pcmPath clearUnfinished:(BOOL)clearUnfinished channels:(int32_t)channels ns_agc:(BOOL)ns_agc completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
/// ogg文件转pcm
/// \param avcPath ogg文件路径
///
/// \param pcmPath pcm文件路径
///
/// \param clearUnfinished 如果任务队列中还有之前未完成的任务，会取消掉
///
/// \param channels 声道数，默认1
///
/// \param ns_agc 是否要做降噪、增益
///
/// \param completionHandler 完成是 true 100；失败是 false -1; 进度是 fale 0-100
///
- (void)oggToPcmWithAvcPath:(NSString * _Nonnull)avcPath pcmPath:(NSString * _Nonnull)pcmPath clearUnfinished:(BOOL)clearUnfinished channels:(int32_t)channels ns_agc:(BOOL)ns_agc completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


/// 声波文件生成工具类
SWIFT_CLASS("_TtC11PlaudBleSDK15JXFileSoundWave")
@interface JXFileSoundWave : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXFileSoundWave * _Nonnull shared;)
+ (JXFileSoundWave * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 是否有未完成任务
- (BOOL)hasAvcToSoundWaveTask SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)generateSoundWaveCancel;
/// 录音文件获取声波
/// \param filePath 录音文件路径
///
/// \param channels 声道数
///
/// \param isOgg 是ogg还是opus/avc?
///
/// \param isMusic 是不是音乐模式
///
/// \param callback 回调
///
- (void)createSoundWave:(NSString * _Nonnull)filePath :(NSInteger)channels :(BOOL)isOgg :(BOOL)isMusic :(void (^ _Nonnull)(BOOL, NSInteger))callback;
/// 录音文件生成声波
/// \param avcPath 未解码文件路径
///
/// \param channels 声道数，默认是1
///
/// \param completionHandler 回调结果和进度
///
- (void)avcToSoundWaveWithAvcPath:(NSString * _Nonnull)avcPath channels:(NSInteger)channels completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


/// 用于流式解码opus以及ogg数据，ogg只能是从录音笔同步的ogg，其他外部协议的不支持
SWIFT_CLASS("_TtC11PlaudBleSDK12JXPcmProcess")
@interface JXPcmProcess : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 单例
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXPcmProcess * _Nonnull shared;)
+ (JXPcmProcess * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 协议
@property (nonatomic, weak) id <JXPcmProcessDelegate> _Nullable delegate;
/// 回调线程，默认主线程
@property (nonatomic, strong) dispatch_queue_t _Nonnull callbackQueue;
/// 重置，开始接收数据前必须重置
/// \param sessionId 录音id（@see BleFile）
///
/// \param channel 声道数（@see BleDevice）
///
/// \param isOgg 是ogg还是opus纯音频未解码数据（@see BleDevice）
///
/// \param nsAgc 是否需要降噪增益（@see BleDevice）
///
- (void)resetWith:(NSInteger)sessionId :(NSInteger)channel :(BOOL)isOgg :(BOOL)nsAgc;
- (void)receiveData:(NSInteger)sessionId :(NSInteger)start :(NSData * _Nonnull)data;
- (void)receiveDataBytes:(NSInteger)sessionId :(NSInteger)start :(NSData * _Nonnull)data;
@end


@interface JXPcmProcess (SWIFT_EXTENSION(PlaudBleSDK)) <JXPcmProcessDelegate>
- (void)onPcmData:(NSInteger)sessionId :(NSInteger)millSec :(NSData * _Nonnull)pcmData;
- (void)onDecodeErr:(NSInteger)millSec;
@end



/// 完整的录音文件声音大小辅助工具类
SWIFT_CLASS("_TtC11PlaudBleSDK15JXRecordVolumer")
@interface JXRecordVolumer : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXRecordVolumer * _Nonnull shared;)
+ (JXRecordVolumer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 多久返回一个峰值？单位是毫秒，一个80B的avc包是20毫秒, 640B的pcm包是20毫秒
/// 不再支持，固定是1秒
@property (nonatomic) NSInteger waveInterval;
/// 音量数组， 内数组包含两个值，第一个是时间（秒），第二个是声音大小（分贝）
/// 例：[[1, 54], [2, 76], [3, 46]]
/// 从第一秒开始
@property (nonatomic, copy) NSArray<NSArray<NSNumber *> *> * _Nonnull volumeArr;
/// 当前走到第几秒
@property (nonatomic, readonly) NSInteger curSec;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 获取一个包的平均音量
/// 如果要自定义，可以用这个方法，否则就用不着
/// \param pcmData 解码后的pcm数据包，单声道是640字节，双声道是1280字节
///
- (NSInteger)averageVolume:(NSData * _Nonnull)pcmData SWIFT_WARN_UNUSED_RESULT;
/// 追加一个解码后的数据包
/// \param start 偏移量
///
/// \param pcmData 解码后的pcm数据包，单声道是640字节，双声道是1280字节
///
/// \param channels 声道
///
- (void)appendWithStart:(NSInteger)start pcmData:(NSData * _Nonnull)pcmData;
/// 重置声音队列（开始新的录音前）
- (void)reset;
@end

@protocol VolumeProtocol;

/// 实时录音声音大小辅助工具类
SWIFT_CLASS("_TtC11PlaudBleSDK18JXRecordingVolumer")
@interface JXRecordingVolumer : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXRecordingVolumer * _Nonnull shared;)
+ (JXRecordingVolumer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <VolumeProtocol> _Nullable delegate;
/// 多久返回一个峰值？单位是毫秒，一个80B的avc包是20毫秒, 640B的pcm包是20毫秒
@property (nonatomic) NSInteger waveInterval;
/// 音量数组， 内数组包含两个值，第一个是时间（秒），第二个是声音大小（分贝）
/// 例：[[1, 54], [2, 76], [3, 46]]
/// 从第一秒开始
@property (nonatomic, readonly, copy) NSArray<NSArray<NSNumber *> *> * _Nonnull volumeArr;
/// 当前走到第几秒
@property (nonatomic, readonly) NSInteger curSec;
/// 当前毫秒值
@property (nonatomic, readonly) NSInteger curMillisec;
/// 当前大小（偏移+data大小）
@property (nonatomic, readonly) NSInteger curFileSize;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 获取一个包的平均音量
/// 如果要自定义，可以用这个方法，否则就用不着
/// \param pcmData 解码后的pcm数据包，640，如果是1280双声道，会转成单声道的640
///
- (CGFloat)averageVolume:(NSData * _Nonnull)pcmData SWIFT_WARN_UNUSED_RESULT;
/// 追加一个解码后的数据包
/// \param start 原始数据偏移量
///
/// \param pcmData 解码后的数据(注意：双声道会变单声道）
///
/// \param channels 声道数
///
- (void)appendWithStart:(NSInteger)start pcmData:(NSData * _Nonnull)pcmData channels:(NSInteger)channels;
/// 追加一个解码后的数据包(单声道）
/// \param millSec 毫秒值
///
/// \param pcmData 解码后的数据
///
- (void)append:(NSInteger)millSec :(NSData * _Nonnull)pcmData;
/// 初始化历史数据
- (void)setOldVolumeMetersWithMeters:(NSArray<NSArray<NSNumber *> *> * _Nonnull)meters;
/// 重置声音队列（开始新的录音前）
- (void)reset;
@end


SWIFT_CLASS("_TtC11PlaudBleSDK17JXWave2PcmProcess")
@interface JXWave2PcmProcess : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 单例
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXWave2PcmProcess * _Nonnull shared;)
+ (JXWave2PcmProcess * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 协议
@property (nonatomic, weak) id <JXPcmProcessDelegate> _Nullable delegate;
/// 回调线程，默认主线程
@property (nonatomic, strong) dispatch_queue_t _Nonnull callbackQueue;
/// 重置，开始接收数据前必须重置
/// \param sessionId 录音id
///
- (void)resetWith:(NSInteger)sessionId;
/// 接收Wave数据
/// \param sessionId 录音id
///
/// \param start 偏移量
///
/// \param data wave数据
///
- (void)receiveData:(NSInteger)sessionId :(NSInteger)start :(NSData * _Nonnull)data;
@end


/// 这个是测试用的
SWIFT_CLASS("_TtC11PlaudBleSDK12JXWaveHelper")
@interface JXWaveHelper : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) JXWaveHelper * _Nonnull shared;)
+ (JXWaveHelper * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tmpPcmPath;)
+ (NSString * _Nonnull)tmpPcmPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull tmpWavPath;)
+ (NSString * _Nonnull)tmpWavPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull leftPath;)
+ (NSString * _Nonnull)leftPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull rightPath;)
+ (NSString * _Nonnull)rightPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull leftWavPath;)
+ (NSString * _Nonnull)leftWavPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull rightWavPath;)
+ (NSString * _Nonnull)rightWavPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull leftLycPath;)
+ (NSString * _Nonnull)leftLycPath SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull rightLycPath;)
+ (NSString * _Nonnull)rightLycPath SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// pcm文件追加文件头转为wave文件
/// \param pcmFilePath pcm文件路径
///
/// \param wavFilePath wave文件路径
///
/// \param channels 声道数，默认1
///
///
/// returns:
/// 是否成功
- (BOOL)pcmFileToWaveWithPcmFilePath:(NSString * _Nonnull)pcmFilePath wavFilePath:(NSString * _Nonnull)wavFilePath channels:(uint32_t)channels simpleRate:(uint32_t)simpleRate SWIFT_WARN_UNUSED_RESULT;
/// 分离左右声道
- (void)divideLeftAndRight:(NSString * _Nonnull)wavePath :(NSString * _Nonnull)leftPath :(NSString * _Nonnull)rightPath handler:(void (^ _Nonnull)(BOOL))handler;
@end


SWIFT_PROTOCOL("_TtP11PlaudBleSDK11OtaProtocol_")
@protocol OtaProtocol
/// ota通知
/// \param uid 标识
///
/// \param status 状态 0 正常，1. 升级失败 2. 版本信息不匹配  3.FLASH写失败 4.文件太大 5.尝试次数过多  6. U盘模式；7.正在录音； 8. U盘剩余空间不足；  9. 正在工作中; 10. G101眼镜仅在充电模式允许升级；11. G101眼镜电池电量不足；12. G101眼镜收到升级协议并准备调整到OTA_MODE; 13. 静默OTA传输成功(固件已接收,下次重启升级); 255：模式不对(录音笔不在录音模式，黑黎三段式开关特有)
///
/// \param errmsg 协议版本4，如果升级成功，这里返回升级后的版本；如果失败，依然返回错误信息。
///
- (void)bleFotaResultWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
/// ota包请求，录音笔请求发送升级包数据
/// \param uid 标识
///
/// \param start 开始位置（字节）
///
/// \param end 结束位置（字节）
///
- (void)bleFotaPackReqWithUid:(NSInteger)uid start:(NSInteger)start end:(NSInteger)end;
/// ota包接收完成
/// \param uid 标识
///
/// \param status 状态 0 正常，1. 升级失败 2. 版本信息不匹配  3.FLASH写失败 4.文件太大 5尝试次数过多  6. U盘模式；7.正在录音； 8. U盘剩余空间不足; 9. 正在工作中; 10. G101眼镜仅在充电模式允许升级；11. G101眼镜电池电量不足；12. G101眼镜收到升级协议并准备调整到OTA_MODE; 13. 静默OTA传输成功(固件已接收,下次重启升级); 255：模式不对(录音笔不在录音模式，黑黎三段式开关特有)
///
/// \param errmsg 协议版本4，如果升级成功，这里返回升级后的版本；如果失败，依然返回错误信息。
///
- (void)bleFotaPackFinWithUid:(NSInteger)uid status:(NSInteger)status errmsg:(NSString * _Nullable)errmsg;
@end


/// 声波文件生成工具类
SWIFT_CLASS("_TtC11PlaudBleSDK15PDFileSoundWave")
@interface PDFileSoundWave : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PDFileSoundWave * _Nonnull shared;)
+ (PDFileSoundWave * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 是否有未完成任务
- (BOOL)hasAvcToSoundWaveTask SWIFT_WARN_UNUSED_RESULT;
/// 取消当前任务（如果有的话），清空任务队列
- (void)generateSoundWaveCancel;
/// 录音文件获取声波
/// \param filePath 录音文件路径
///
/// \param channels 声道数
///
/// \param isOgg 是ogg还是opus/avc?
///
/// \param isMusic 是不是音乐模式
///
/// \param callback 回调
///
- (void)createSoundWave:(NSString * _Nonnull)filePath :(NSInteger)channels :(BOOL)isOgg :(BOOL)isMusic :(void (^ _Nonnull)(BOOL, NSInteger))callback;
/// 录音文件生成声波
/// \param avcPath 未解码文件路径
///
/// \param channels 声道数，默认是1
///
/// \param completionHandler 回调结果和进度
///
- (void)avcToSoundWaveWithAvcPath:(NSString * _Nonnull)avcPath channels:(NSInteger)channels completionHandler:(void (^ _Nonnull)(BOOL, NSInteger))completionHandler;
@end


/// 完整的录音文件声音大小辅助工具类
SWIFT_CLASS("_TtC11PlaudBleSDK15PDRecordVolumer")
@interface PDRecordVolumer : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PDRecordVolumer * _Nonnull shared;)
+ (PDRecordVolumer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// 多久返回一个峰值？单位是毫秒，一个80B的avc包是20毫秒, 640B的pcm包是20毫秒
/// 不再支持，固定是1秒
@property (nonatomic) NSInteger waveInterval;
/// 音量数组， 内数组包含两个值，第一个是时间（秒），第二个是声音大小（分贝）
/// 例：[[1, 54], [2, 76], [3, 46]]
/// 从第一秒开始
@property (nonatomic, copy) NSArray<NSArray<NSNumber *> *> * _Nonnull volumeArr;
/// 当前走到第几秒
@property (nonatomic, readonly) NSInteger curSec;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 获取一个包的平均音量
/// 如果要自定义，可以用这个方法，否则就用不着
/// \param pcmData 解码后的pcm数据包，单声道是640字节，双声道是1280字节
///
- (NSInteger)averageVolume:(NSData * _Nonnull)pcmData SWIFT_WARN_UNUSED_RESULT;
/// 追加一个解码后的数据包
/// \param start 偏移量
///
/// \param pcmData 解码后的pcm数据包，单声道是640字节，双声道是1280字节
///
/// \param channels 声道
///
- (void)appendWithStart:(NSInteger)start pcmData:(NSData * _Nonnull)pcmData;
/// 重置声音队列（开始新的录音前）
- (void)reset;
@end

@protocol PDVolumeProtocol;

/// 实时录音声音大小辅助工具类
SWIFT_CLASS("_TtC11PlaudBleSDK18PDRecordingVolumer")
@interface PDRecordingVolumer : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PDRecordingVolumer * _Nonnull shared;)
+ (PDRecordingVolumer * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <PDVolumeProtocol> _Nullable delegate;
/// 多久返回一个峰值？单位是毫秒，一个80B的avc包是20毫秒, 640B的pcm包是20毫秒
@property (nonatomic) NSInteger waveInterval;
/// 音量数组， 内数组包含两个值，第一个是时间（秒），第二个是声音大小（分贝）
/// 例：[[1, 54], [2, 76], [3, 46]]
/// 从第一秒开始
@property (nonatomic, readonly, copy) NSArray<NSArray<NSNumber *> *> * _Nonnull volumeArr;
/// 当前走到第几秒
@property (nonatomic, readonly) NSInteger curSec;
/// 当前毫秒值
@property (nonatomic, readonly) NSInteger curMillisec;
/// 当前大小（偏移+data大小）
@property (nonatomic, readonly) NSInteger curFileSize;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 获取一个包的平均音量
/// 如果要自定义，可以用这个方法，否则就用不着
/// \param pcmData 解码后的pcm数据包，640，如果是1280双声道，会转成单声道的640
///
- (CGFloat)averageVolume:(NSData * _Nonnull)pcmData SWIFT_WARN_UNUSED_RESULT;
/// 追加一个解码后的数据包
/// \param start 原始数据偏移量
///
/// \param pcmData 解码后的数据(注意：双声道会变单声道）
///
/// \param channels 声道数
///
- (void)appendWithStart:(NSInteger)start pcmData:(NSData * _Nonnull)pcmData channels:(NSInteger)channels;
/// 追加一个解码后的数据包(单声道）
/// \param millSec 毫秒值
///
/// \param pcmData 解码后的数据
///
- (void)append:(NSInteger)millSec :(NSData * _Nonnull)pcmData;
/// 初始化历史数据
- (void)setOldVolumeMetersWithMeters:(NSArray<NSArray<NSNumber *> *> * _Nonnull)meters;
/// 重置声音队列（开始新的录音前）
- (void)reset;
@end


SWIFT_PROTOCOL("_TtP11PlaudBleSDK16PDVolumeProtocol_")
@protocol PDVolumeProtocol
/// 时长该表
- (void)onDurationWithMillisec:(NSInteger)millisec;
/// 回到声音大小
/// \param sec 第几秒？ 从1开始，每个整数秒会有一个之前一秒钟的平均音量
///
/// \param volume 单位分贝
///
- (void)onVolumeWithSec:(NSInteger)sec volume:(NSInteger)volume;
/// 回到声音大小
/// \param mescIndex 每二十毫秒为一个间隔，从 0 开始，每二十毫秒对应一个分贝值
///
/// \param volume 单位分贝
///
- (void)onVolumePerTwentyMsecWithMescSecond:(NSInteger)mescSecond volume:(NSInteger)volume;
@end



/// 录音笔固件升级信息
SWIFT_CLASS("_TtC11PlaudBleSDK10UpdateInfo")
@interface UpdateInfo : NSObject
/// 哪个录音笔？
@property (nonatomic, copy) NSString * _Nonnull sn;
/// 固件版本 （例：T0004）
@property (nonatomic, copy) NSString * _Nonnull swVersion;
/// 当前版本 （例：V1.0.0）
@property (nonatomic, copy) NSString * _Nonnull currentVersion;
/// 目标版本， 为空表示没有升级版本
@property (nonatomic, copy) NSString * _Nonnull version;
/// 下载地址
@property (nonatomic, copy) NSString * _Nonnull url;
/// 大小
@property (nonatomic) NSInteger size;
/// 更新信息
@property (nonatomic, copy) NSString * _Nonnull modifyDesc;
/// “本次升级大约需要10分钟”
@property (nonatomic, copy) NSString * _Nonnull updateDesc;
@property (nonatomic, copy) NSString * _Nonnull updatePreTip;
@property (nonatomic, copy) NSString * _Nonnull updatingTip;
@property (nonatomic, copy) NSString * _Nonnull failureTip;
/// 初始版本
@property (nonatomic, copy) NSString * _Nonnull fromVersion;
/// 目标版本
@property (nonatomic, copy) NSString * _Nonnull toVersion;
/// md5校验完整性
@property (nonatomic, copy) NSString * _Nonnull md5;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// 当前录音笔是否需要升级固件？
- (BOOL)hasNewVersion:(BleDevice * _Nonnull)device SWIFT_WARN_UNUSED_RESULT;
/// 校验MD5， path是下载后升级包的路径
- (BOOL)checkMD5WithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
/// 方便打印
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP11PlaudBleSDK14VolumeProtocol_")
@protocol VolumeProtocol
/// 时长该表
- (void)onDurationWithMillisec:(NSInteger)millisec;
/// 回到声音大小
/// \param sec 第几秒？ 从1开始，每个整数秒会有一个之前一秒钟的平均音量
///
/// \param volume 单位分贝
///
- (void)onVolumeWithSec:(NSInteger)sec volume:(NSInteger)volume;
@end

@class SwiftyRSAPublicKey;
@class EncryptedMessage;
@class PrivateKey;
enum DigestType : NSInteger;
@class Signature;
@class VerificationResult;

SWIFT_CLASS_NAMED("_objc_ClearMessage")
@interface ClearMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithString:(NSString * _Nonnull)string using:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nullable)stringWithEncoding:(NSUInteger)rawEncoding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (EncryptedMessage * _Nullable)encryptedWith:(SwiftyRSAPublicKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (Signature * _Nullable)signedWith:(PrivateKey * _Nonnull)key digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (VerificationResult * _Nullable)verifyWith:(SwiftyRSAPublicKey * _Nonnull)key signature:(Signature * _Nonnull)signature digestType:(enum DigestType)digestType error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_EncryptedMessage")
@interface EncryptedMessage : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (ClearMessage * _Nullable)decryptedWith:(PrivateKey * _Nonnull)key padding:(SecPadding)padding error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSBundle;

SWIFT_CLASS_NAMED("_objc_PrivateKey")
@interface PrivateKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_PublicKey")
@interface SwiftyRSAPublicKey : NSObject
@property (nonatomic, readonly) SecKeyRef _Nonnull reference;
@property (nonatomic, readonly, copy) NSData * _Nullable originalData;
- (NSString * _Nullable)pemStringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSData * _Nullable)dataAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)base64StringAndReturnError:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithData:(NSData * _Nonnull)data error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithReference:(SecKeyRef _Nonnull)reference error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemEncoded:(NSString * _Nonnull)pemString error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithPemNamed:(NSString * _Nonnull)pemName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDerNamed:(NSString * _Nonnull)derName in:(NSBundle * _Nonnull)bundle error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<SwiftyRSAPublicKey *> * _Nonnull)publicKeysWithPemEncoded:(NSString * _Nonnull)pemString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("_objc_Signature")
@interface Signature : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull base64String;
@property (nonatomic, readonly, copy) NSData * _Nonnull data;
- (nonnull instancetype)initWithData:(NSData * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithBase64Encoded:(NSString * _Nonnull)base64String error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DigestType, open) {
  DigestTypeSha1 = 0,
  DigestTypeSha224 = 1,
  DigestTypeSha256 = 2,
  DigestTypeSha384 = 3,
  DigestTypeSha512 = 4,
};


SWIFT_CLASS_NAMED("_objc_VerificationResult")
@interface VerificationResult : NSObject
@property (nonatomic, readonly) BOOL isSuccessful;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
